### ISSUE TITLE
ClientRegistrations#fromIssuerLocation should have shorter (or configurable) Http Connect/Read timeouts

### ISSUE THREAD

**Issue by Kehrlann** [spring-projects/spring-security#11197]
**Expected Behavior**

When using `ClientRegistrations.fromIssuerLocation("http://192.0.2.0")` or any non-responding address[1], the http connect timeout should be "reasonable", in seconds so that users get quick feedback when a issuerUri just doesn't respond. Reasonable _may_ be somewhere between 5 and 10s.

Or the `ClientRegistrations.rest` RestTemplate could be configurable.

**Current Behavior**

The current timeout is whatever the default timeout is for RestTemplate / underlying HTTP client implementation. In a "default" Boot application, that timeout is 75s. This means the application will hang for 75 seconds, and Tomcat won't even start up. 

That is too long in certain contexts, e.g. a Boot app deployed to Kubernetes. The app would take 75 seconds to respond, which could be longer than the user's readiness probe - the pod would get thrashed without giving useful information to the user.

**Context**

We have seen this issue in k8s deployments, where our pods would crash because a DNS record was (incorrectly) changed and an OIDC issuer did not respond anymore.

**Sample**

A Boot app with OAuth2 login enabled, and the following config:

```yml
spring:
  security:
    oauth2:
      client:
        registration:
          default:
            client-id: "foo"
            client-secret: "bar"
            provider: my-provider
        provider:
          my-provider:
            issuer-uri: https://192.0.2.0 # or any other non-responding IP
```

This can be reproduced programmatically by calling `ClientRegistrations.fromIssuerLocation("http://192.0.2.0");`

Happy to contribute a PR.

#### Footnotes

[1] Used `192.0.2.0` as [RFC5737 - IPv4 Address Blocks Reserved for Documentation](https://www.rfc-editor.org/rfc/rfc5737), works as an example for MacOS but I haven't tried on other systems.
