### ISSUE TITLE
Logout request with session invalidation not working

### ISSUE THREAD

**Issue by adamalexandru4** [spring-projects/spring-security#11271]
**Describe the bug**
Configuring OidcClientInitiatedServerLogoutSuccessHandler as a logoutSuccessHandler and WebSessionServerLogoutHandler + SecurityContextServerLogoutHandler as logoutHandlers is not working. 
With default logoutHandlers everything works fine but sessions won't be invalidated on gateway, only on Keycloak.

**To Reproduce**
Spring Boot 2.7.0 with following dependencies:
Spring Cloud Gateway
Spring OAuth2 Client
Spring Session Data Redis

I'm working on BFF setup and I configured Spring Cloud Gateway as OAuth2 client:

application.yaml: 
```yaml
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8090/realms/example-realm
        registration:
          keycloak-client:
            provider: keycloak
            scope: openid
            client-id: example-client
            client-secret: example-secret
            authorization-grant-type: authorization_code
```

```java
@Configuration
@RequiredArgsConstructor
public class SecurityConfig {

    final ReactiveClientRegistrationRepository clientRegistrationRepository;

    @Value("${server.url}")
    final String serverUrl;

    @Bean
    public SecurityWebFilterChain springSecurityFilterChain(ServerHttpSecurity http) {
        DelegatingServerLogoutHandler logoutHandler = new DelegatingServerLogoutHandler(
                new WebSessionServerLogoutHandler(), new SecurityContextServerLogoutHandler()
        );

        http.authorizeExchange()
                .anyExchange().authenticated()
                .and()
                .oauth2Login()
                .authenticationFailureHandler(oidcAuthenticationFailureHandler())
                .authorizedClientRepository(authorizedClientRepository())
                .and()
                .logout()
                .logoutHandler(logoutHandler)
                .logoutSuccessHandler(oidcLogoutSuccessHandler());

        return http.build();
    }

    @Bean
    public ServerLogoutSuccessHandler oidcLogoutSuccessHandler() {
        OidcClientInitiatedServerLogoutSuccessHandler successHandler = new OidcClientInitiatedServerLogoutSuccessHandler(clientRegistrationRepository);
        successHandler.setPostLogoutRedirectUri(serverUrl);
        return successHandler;
    }

    @Bean
    public ServerAuthenticationFailureHandler oidcAuthenticationFailureHandler() {
        return new RedirectServerAuthenticationFailureHandler(serverUrl);
    }

    /**
     * https://github.com/spring-projects/spring-security/issues/7889
     */
    @Bean
    public ServerOAuth2AuthorizedClientRepository authorizedClientRepository() {
        return new WebSessionServerOAuth2AuthorizedClientRepository();
    }
```

**Expected behavior**
When I browse to http://localhost:8085/logout the default logout page shows. I press the log out button but the logout flow fails.
The sessions on gateway and keycloak are not invalidated and I receive an 500 error.

```
2022-05-22 20:36:30.962 ERROR [TraceId=,SpanId=] 34225 --- [ioEventLoop-5-1] a.w.r.e.AbstractErrorWebExceptionHandler : [8a2d7a53-6]  500 Server Error for HTTP POST "/logout"

java.lang.IllegalStateException: Session was invalidated
	at org.springframework.session.data.redis.ReactiveRedisSessionRepository.lambda$save$1(ReactiveRedisSessionRepository.java:128) ~[spring-session-data-redis-2.6.3.jar:2.6.3]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ⇢ org.springframework.security.web.server.authentication.logout.LogoutWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.web.server.savedrequest.ServerRequestCacheWebFilter [DefaultWebFilterChain]
```
