### ISSUE TITLE
Fix slack notifications with external PRs

### ISSUE THREAD

**Issue by sjohnr** [spring-projects/spring-security#11346]
See Gamesight/slack-workflow-status#38

**Comment by sjohnr** [comment]
This fix was unsuccessful. Reopening to investigate further.

**Comment by sjohnr** [comment]
Upon investigation, the existing fix put in place should have resolved the issue.

**Notes:**

The current step looks like this:

```yml
      - name: Send Slack message
        # Workaround while waiting for Gamesight/slack-workflow-status#38 to be fixed
        # See https://github.com/Gamesight/slack-workflow-status/issues/38
        uses: sjohnr/slack-workflow-status@9eb3eb361c03f8bb9271782f987f472adfc31056
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          channel: '#spring-security-ci'
          name: 'CI Notifier'
```

This step points to [this commit](https://github.com/sjohnr/slack-workflow-status/commit/9eb3eb361c03f8bb9271782f987f472adfc31056) in a fork of the `slack-workflow-status` action, but GitHub doesn't seem to be using this commit.

The fix filters out PRs from external forks of the project by comparing the repository url of the pull request to the repository url of the workflow run.

See an example of the [workflow run](https://api.github.com/repos/spring-projects/spring-security/actions/runs/2497553420) API response the action is working from. The action also queries the [jobs for the workflow run](https://api.github.com/repos/spring-projects/spring-security/actions/runs/2497553420/jobs).
