### ISSUE TITLE
Use Spring Gradle Build Action

### ISSUE THREAD

**Issue by sjohnr** [spring-projects/spring-security#11630]
We should switch from `gradle/gradle-build-action@v2` to `spring-io/spring-gradle-build-action@v1` (see [README](https://github.com/spring-io/spring-gradle-build-action/blob/main/README.md)).

Replace the following steps:

```yaml
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '17'
      - name: Setup gradle user name
        run: |
          mkdir -p ~/.gradle
          echo 'systemProp.user.name=spring-builds+github' >> ~/.gradle/gradle.properties
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        env:
          GRADLE_USER_HOME: ~/.gradle
```

with:

```yaml
      - name: Set up gradle
        uses: spring-io/spring-gradle-build-action@v1
        with:
          java-version: '17'
          distribution: 'temurin'
```

**Note:** Using `~/.gradle` as the gradle home seems to interfere with the build cache, so this may speed up the build.
