### ISSUE TITLE
Unable to use oAuth login with ES256 due to ReactiveOidcIdTokenDecoderFactory locked to RS256

### ISSUE THREAD

**Issue by thomasmillercf** [spring-projects/spring-security#11799]
**Describe the bug**
The current identity provider i am using only supports ES256, and i was unable to finish the login flow as i would get `unsupported algorithm of ES256`. Digging further I have found the class `ReactiveOidcIdTokenDecoderFactory.class` locks the algo to RS256 even without checking if its supported in the jwks.

Looking into the openid spec of` https://openid.net/specs/openid-financial-api-part-2-1_0.html`  it say ES256 should be used and RS265 should not be even though in openid spec v1 it says RS265 should be the default. 
Either way i should be able to use ES256

**To Reproduce**

I used the cloudentity as my provider, however any provider which only supports ES256 will recreate the issue. 

```
spring:
  security:
    oauth2:
      client:
        registration:
          cloudentity:
            provider: cloudentity
            client-authentication-method: none
            client-id: test
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          cloudentity:
            token-uri: https://xxxxx.eu.authz.cloudentity.io/xxxxx/test/oauth2/token
            authorization-uri: https://xxxxx.eu.authz.cloudentity.io/xxxxx/test/oauth2/authorize
            issuer-uri: https://xxxxx.eu.authz.cloudentity.io/xxxxx/test
            jwk-set-uri: https://xxxxx.eu.authz.cloudentity.io/xxxxx/test/.well-known/jwks.json
            user-name-attribute: name
            user-info-uri: https://xxxxx.eu.authz.cloudentity.io/xxxxx/test/userinfo
```

Go to https://xxx.eu.authz.cloudentity.io/xxx/test/oauth2/authorize?response_type=code&client_id=test&redirect_uri=http://localhost:8080/login/oauth2/code/cloudentity

Then you will get ``nsupported algorithm of ES256`

**Expected behavior**

When registering the jwt decoder it should check the jwks set  for which algo to use, where it defaults to RS256 then if its not found use the first one which the jwks set

Or
I should be able to configure the algo via

spring:
  security:
    oauth2:
      client:
        provider:
          cloudentity:
            algo: es256
