### ISSUE TITLE
Support refresh_token as a configuration property similar to client_credentials in OAuth2 for WebClient

### ISSUE THREAD

**Issue by sickan90** [spring-projects/spring-security#11884]
### Summary
I have to consume a 3rd party REST API. This API does not support client_credentials authentication grant type. Instead they have a process of getting a long-lived refresh token. However, it is not easy to integrate the refresh token into the WebClient request to get an access token. 

Was hoping to just configure the same way I would given a client_credentials flow. Something similar to:

```yml
spring:
  security:
    oauth2:
      client:
        registration:
          external-api:
            client-id: <client_id>
            client-secret: <client_secret>
            client-authentication-method: CLIENT_SECRET_BASIC
            refresh_token: <refresh_token>
            authorization-grant-type: refresh_token
        provider:
          external-api:
            token-uri: https://external-api.com/oauth2/token
```

### Expected Behavior

Configuration or guide that shows how this can be achieved.
