### ISSUE TITLE
SecureHeaders adds content-security-policy by default

### ISSUE THREAD

**Issue by robert-gdv** [spring-projects/spring-security#11925]
The filter SecureHeaders adds a content-security-policy header.
This is contrary to the [documentation saying "Spring Security does not add by default](https://docs.spring.io/spring-security/reference/5.7.3/reactive/exploits/headers.html#webflux-headers-csp)
It's also not documented, how do disable it (from config).

**To Reproduce**
Start a Webserver serving come content.
Add SecureHeaders filter to a route to that webserver check the response headers.

```yaml
webserver.url: "http://localhost:8080"
spring:
  cloud:
    gateway:
      routes:
        - id: webserver
          uri: ${webserver.url}
          predicates:
            - Path=/**
            - Method=GET
          filters:
            - SecureHeaders
```

**Expected behavior**
The response doesn't contain content-security-policy

**Sample**
https://github.com/robert-gdv/issue-spring-csp-header
