### ISSUE TITLE
Verification Credentials with SAML2 Metadata in Spring Security 

### ISSUE THREAD

**Issue by sumeetpri** [spring-projects/spring-security#13755]
I'm using Spring Security SAML2 for authentication in my application. We're populating the identity provider details using its metadata URL. Based on my understanding, when reading the IDP metadata from URL, a relying party registration will be automatically created with verification credential. Consequently, there's no need to manually configure verification credentials if the metadata URI is supplied to the asserting party. Is my understanding correct?

```
spring:
  security:
    saml2:
      relyingparty:
        registration:
          okta:
            entity-id: https://my-application.com/okta/
            identityprovider:
              entity-id: http://www.okta.com/787hjhg
              singlesignon.sign-request: true
            assertingparty:
              metadata-uri: https://dev-678.okta.com/app/exka/sso/saml/metadata
            decryption:
              credentials:
                - private-key-location: classpath:my-private-decryption.key
                  certificate-location: classpath:my-public-decryption.crt
            signing:
              credentials:
                - private-key-location: classpath:my-private-signing.key
                  certificate-location: classpath:my-private-signing.key
            acs:
              location: https://my-application.com/saml2/SSO

```
I assume if my metadata URL has IDP public key then I do not require to configure like

```
spring:
  security:
    saml2:
      relyingparty:
        registration:
          okta:
            entity-id: https://my-application.com/okta/
            identityprovider:
              entity-id: http://www.okta.com/787hjhg
              singlesignon.sign-request: true
            assertingparty:
              metadata-uri: https://dev-678.okta.com/app/exka/sso/saml/metadata
              verification:
                credentials:
                  - certificate-location: classpath:idp-public.crt
            decryption:
              credentials:
                - private-key-location: classpath:my-private-decryption.key
                  certificate-location: classpath:my-public-decryption.crt
            signing:
              credentials:
                - private-key-location: classpath:my-private-signing.key
                  certificate-location: classpath:my-private-signing.key
            acs:
              location: https://my-application.com/saml2/SSO

```
