### ISSUE TITLE
Support different OIDC issuer hostnames for frontend/backend endpoints

### ISSUE THREAD

**Issue by heruan** [spring-projects/spring-security#14633]
**Expected Behavior**

When the OIDC provider uses different hostnames from frontend and backend endpoints, fetching metadata from the configure issuer hostname does not fail.

**Current Behavior**

If the frontend and backend hostnames differs when fetching metadata, a validation exception is thrown.

**Context**

Consider a Spring application running inside a Kubernetes cluster, and it needs to authenticate against an OIDC server inside the same cluster (say Keycloak). Hostnames used inside the cluster are different from the public ones, and this is supported by Keycloak (frontend and backend hostnames can be different).

The Spring app has this configuration:

```
spring.security.oauth2.client.provider.keycloak.issuer-uri: http://internal:8180/realms/foo
```

When fetching metadata from there, Keycloak returns:

```json
{
    "issuer": "https://external/realms/foo",
    "authorization_endpoint": "https://external/realms/foo/protocol/openid-connect/auth",
    "token_endpoint": "http://internal:8180/realms/foo/protocol/openid-connect/token",
    "introspection_endpoint": "http://internal:8180/realms/foo/protocol/openid-connect/token/introspect",
    "userinfo_endpoint": "http://internal:8180/realms/foo/protocol/openid-connect/userinfo",
    "end_session_endpoint": "https://external/realms/foo/protocol/openid-connect/logout",
    "...": "..."
}
```

As expected, the frontend endpoints use `https://external` and backend endpoints use `http://internal:8180`.

The problem is that when fetching metadata, Spring fails here:

https://github.com/spring-projects/spring-security/blob/9c6b5f90f7787404922450d9ec559415c55ec4c3/oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/registration/ClientRegistrations.java#L246-L248

Fetching metadata from the issuer is necessary since some endpoints are read only from metadata, e.g the `end_session_endpoint`:

https://github.com/spring-projects/spring-security/blob/9c6b5f90f7787404922450d9ec559415c55ec4c3/oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/oidc/web/logout/OidcClientInitiatedLogoutSuccessHandler.java#L79-L80

But also other back-channel endpoints without configuration properties in `application.yaml`.

Since I know both internal and external hostnames, how can I make Spring Security fetch metadata from the internal issuer hostname and accept the external hostname in metadata?

Note: a similar scenario has been solved for JWT decoders in https://github.com/spring-projects/spring-security/issues/10309

**Comment by heruan** [comment]
Hey @jzheaux thanks for the feedback! I'm not able to query using the external URI, so I'd need another approach. How would the `fromMetadata(Map)` work with other properties from the Boot configuration, e.g. `client-id`, `client-secret` or `scope`? Take for example this YAML:

```yaml
spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://internal:8180/realms/foo
        registration:
          keycloak:
            client-id: my-client
            client-secret: my-secret
            scope:
            - openid
```

With the current implementation the `OAuth2ClientPropertiesMapper` merges the metadata fetched from the issuer-uri with the properties in the `registration` subtree. Would it be possible to hook up your suggested approach in the mapper, so that if a `issuer-uri` is not provided for a registration there's still a chance to get a builder with provided metadata?

I suppose that would be somewhere around here: [OAuth2ClientPropertiesMapper.java#L71-L74](https://github.com/spring-projects/spring-boot/blob/2c4fb5baaa5af931730b610ecfee2645586ba0f1/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/security/oauth2/client/OAuth2ClientPropertiesMapper.java#L71-L74)

I need this to be configuration based since applications run in a cluster and configuration is provisioned with config-maps so if I add code it should be generic enough to work with different configurations.

**Comment by heruan** [comment]
I've tried different approaches to this without much luck. Only configuring with Boot properties successfully configures everything needed for OIDC to work properly, e.g. scopes, tokens, back-channel logout, etc.

That part of the spec you mentioned looks to be known to be problematic, as it doesn't take into account valid scenarios like the one I described where the app communicates with the issuer with a backend URL. Quarkus provides a way to [skip issuer validation](https://github.com/quarkusio/quarkus/issues/16384) in that sense and also Vault is [dealing with this](https://github.com/hashicorp/vault/issues/25024).

Would it be acceptable to have a Boot property to specify the issuer value expected from metadata to perform validation?

```yaml
spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://internal:8180/realms/foo
            metadata-issuer: https://external/realms/foo
```

**Comment by heruan** [comment]
@jzheaux any further comments on this? It's also being discussed in https://github.com/keycloak/keycloak/issues/24252#issuecomment-2018949211 first and then https://github.com/keycloak/keycloak/issues/29783 for a Keycloak-specific approach, but I read mentions of the same topic being an issue in Vault and other OIDC based projects.

**Comment by chvndb** [comment]
I'm having the same issue, any solution or workaround for now?

**Comment by lyca** [comment]
> I'm having the same issue, any solution or workaround for now?

The easiest "workaround" is to not set the `issuer-uri` at all and instead only configure the `jwk-set-uri`.

```yaml
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://idp.example.org/.well-known/jwks.json
```

Without the `issuer-uri` configured, the demanded check from [4.3. OpenID Provider Configuration Validation](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfigurationValidation) would not be made.

> The issuer value returned MUST be identical to the Issuer URL that was directly used to retrieve the configuration information.

Also the issuer validation with the [JwtIssuerValidator](https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/oauth2/jwt/JwtIssuerValidator.html) will not be active. If the validation is needed, one could bring it back by configuring the [JwtDecoder](https://docs.spring.io/spring-security/reference/servlet/oauth2/resource-server/jwt.html#oauth2resourceserver-jwt-validation) as a bean.

**Comment by vbbonev** [comment]
I have the same problem (Spring boot + Keycloak  behind nginx reverse proxy -> all in docker containers). The workaround that I use is to set alias on the nginx container (alias=external.com) and from spring --> keycloak.issuer-uri: https://external.com.....

**Comment by heruan** [comment]
I have created PR #15716 to address this with the minimum changes required to support the mentioned scenarios. If it gets merged, additional support for e.g. Spring Boot configuration properties could be discussed.

**Comment by heruan** [comment]
> The easiest "workaround" is to not set the `issuer-uri` at all and instead only configure the `jwk-set-uri`.

This workaround only applies for a resource server, while for OIDC also other endpoints are fetched from the issuer.

**Comment by chvndb** [comment]
> The easiest "workaround" is to not set the `issuer-uri` at all and instead only configure the `jwk-set-uri`.

Indeed, this only works for a resource server. The solution of @vbbonev is best when using plain docker containers. I am using Kubernetes, my currentworkaround is to add a rewrite rule to coredns, e.g.:

`rewrite name ${issuer-uri} nginx-service.default.svc.cluster.local`

I tested this locally and using this on Azure (AKS) in production:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
    track.override: |
          rewrite name ${issuer-uri} nginx-service.default.svc.cluster.local
```

Obviously with your issuer-uri provided.

This would not be needed anymore with the PR of @heruan.
