### ISSUE TITLE
Add support for requesting protected resources with RestClient via a ServletBearerExchangeFilterFunction or equivalent

### ISSUE THREAD

**Issue by azizabah** [spring-projects/spring-security#15820]
**Expected Behavior**
It would be nice if the RestClient supported an equivalent of ServletBearerExchangeFilterFunction. This would allow us to easily grab a user's bearer token and pass that on to subsequent client calls without having to explicitly grab the header and token etc. 

**Current Behavior**
Currently I can implement this very easily for a WebClient like this:
```
@Bean
  public WebClient profileServiceWebClient(WebClient.Builder webClientBuilder) {
    return webClientBuilder.filter(new ServletBearerExchangeFilterFunction()).baseUrl(profileServiceBaseUrl)
        .defaultHeader(HttpHeaders.CONTENT_TYPE, MediaType.APPLICATION_JSON_VALUE).build();
  }
```
As far as I know there is no equivalent implementation for the new RestClient. 
**Context**
This issue is seen as a pretty large blocker for code bases that have to pull a dependency on Spring Boot Starter Webflux (or equivalent) to use WebClient when they are not using a reactive code base. It would be much more preferable to not have to pull that dependency and not have to use reactive code inside a non-reactive code base.

**Comment by ch4mpy** [comment]
What about making the `ServletOAuth2AuthorizedClientExchangeFilterFunction` and `ServerOAuth2AuthorizedClientExchangeFilterFunction` - as well as their `OAuth2ClientHttpRequestInterceptor` equivalent for `RestClient` - more versatile?

As I understand, these `ExchangeFilterFunction` / `ClientHttpRequestInterceptor` serve two purposes:
1. get a Bearer from somewhere: an OAuth2 client `registration` in the case of the classes listed above, and the `Authentication` in the security context when forwarding the token of an `oauth2ResourceServer` request.
2. optionally handle authorization failure with a `(Reactive)OAuth2AuthorizationFailureHandler`

Maybe could the framework provide a few implementations for each of these two strategies? This would lead to `ServletBearerExchangeFilterFunction`, `ServerBearerExchangeFilterFunction`, and  `BearerHttpRequestInterceptor` with maybe `NoOpAuthorizationFailureHandler` and `RemoveAuthorizedClient(Reactive)OAuth2AuthorizationFailureHandler`.

We could expect Spring Boot to auto-configures named interceptor / filter beans with the chosen strategies based on application properties. 

`WebClient` / `RestClient` named beans could be exposed and pre-configured with such filter / interceptors. Something like:
```yaml
spring:
  web-clients:
    client-a:
      base-url: http://localhost:8081
      bearer:
        registration: registration-a
        failure-handler: remove-authorized-client
    client-b:
      base-url: http://localhost:8082
      bearer:
        forward: true
        failure-handler: no-op
```
```java
@RestController
@RequiredArgsConstructor
static class MyRestController {
  private final WebClient clientA; // pre-configured with client-a properties above
  private final WebClient clientB; // pre-configured with client-b properties above
}
```
Maybe, could Bearer forwarding be the default on resource servers when the `spring.rest-clients.{clientId}.bearer.registration` is empty. `no-op` could probably be the default for Bearer forwarding and `remove-authorized-client` the default when a client registration is used.

To go even further, we could dream of the recent `@HttExchange` service proxy factory being involved in the picture:
```yaml
spring:
  rest-proxy:
    service-a:
      client-id: client-a
      http-exchange-interface: com.c4-soft.RestServiceA
```
```java
@HttpExchange
public interface RestServiceA {
  @GetExchange(url = "/{realm}/users/count")
  Mono<Long> getTotalUsersCount(@PathVariable(name = "realm") String realm);
}
```java
This would expose a `serviceA` bean of `RestServiceA` type using the `clientA` WebClient bean pre-configured above to forward the `Bearer` token in the security context!
```
@RestController
@RequiredArgsConstructor
static class MyRestController {
  private final RestServiceA serviceA;

  @GetMapping("users-count")
  Mono<Long> getUsersCount(@RequestParam String realm) {
    return serviceA.getTotalUsersCount(realm);
  }
}
```

I'm currently working on that in [this starter](https://github.com/ch4mpy/spring-addons#spring-addons-starter-rest), but of course, I'd love that to be in the core framework (and reduce the number of features I have to maintain ;).

**Comment by sjohnr** [comment]
@ch4mpy thanks for providing your thoughts! Most of the features you're sketching out here would be applicable to Spring Boot, not Spring Security. You are welcome to open an issue there. I agree that configuration properties are nice, but this style of feature is akin to programming with yaml, which I don't believe is specifically the purpose of Spring Boot's auto-configuration features. You would need to clarify that with the Boot team however, as I can't speak for them. Of course, it's fine for a 3rd party library such as yours to provide them though.

> Maybe could the framework provide a few implementations for each of these two strategies?

Let's stay focused on this ticket which is aimed at providing a `ClientHttpRequestInterceptor` for OAuth2 Resource Server. If you have other ideas, please open a new issue with those.

**Comment by ch4mpy** [comment]
@sjohnr I know by experience that Spring Boot team will decline security features if Spring Security team doesn't see their value (and also that most of Boot code related to security is written by Spring Security team members). So, I'll save everybody time and keep working on my lib because on my daily work implementing REST backends with OAuth2 micro-services, hiding configuration details with Boot & YAML saves a lot of code not related to business logic (and sometimes eases the migration to newer versions of Spring Security with breaking changes).

**Comment by ch4mpy** [comment]
In my starter, what I use as `ClientHttpRequestInterceptor` for forwarding an access token in the security-context of a resource server is the following:
```java
ClientHttpRequestInterceptor forwardingClientHttpRequestInterceptor() {
  return (HttpRequest request, byte[] body, ClientHttpRequestExecution execution) -> {
    final var auth = SecurityContextHolder.getContext().getAuthentication();
    if (auth != null && auth.getPrincipal() instanceof AbstractOAuth2Token oauth2Token) {
      request.getHeaders().setBearerAuth(oauth2Token.getTokenValue());
    }
    return execution.execute(request, body);
  };
}
```

I have a sample in [this repo](https://github.com/ch4mpy/rest-showcase):
- [with just Spring Boot "official" starters](https://github.com/ch4mpy/rest-showcase/blob/master/rest-showcase-chouette-api-servlet/src/main/java/com/c4soft/showcase/rest/RestConfiguration.java) and the hand-written `RestClient` bean definition calling the code above
- [with my starter](https://github.com/ch4mpy/rest-showcase/blob/master/rest-showcase-chouette-api-servlet-addons/src/main/java/com/c4soft/showcase/rest/RestConfiguration.java) and auto-configured `RestClient` beans as defined in the following properties:
```yaml
com:
  c4-soft:
    springaddons:
      rest:
        client:
          machin-client:
            base-url: http://localhost:${machin-api-port}
            authorization:
              oauth2:
                forward-bearer: true
          bidule-client:
            base-url: http://localhost:${bidule-api-port}
            authorization:
              oauth2:
                oauth2-registration-id: bidule-registration
```
You're interested in the `machin-client` which is using the `forward-bearer` strategy for providing the authorization `Bearer` token.

@sjohnr I just moved auto-configuration requests to [this Boot ticket](https://github.com/spring-projects/spring-boot/issues/42963).
