### ISSUE TITLE
Oauth2 jwt not work if no Authorization attribute in http header or Authorization not start with 'Bearer '

### ISSUE THREAD

**Issue by tongshushan** [spring-projects/spring-security#15844]
Hello,
I use Oauth2 jwt connected to the keycloak server to verify the user's jwt token, but I find if there's no Authorization attribute in the http header  or the no the keyword **_Bearer_** in token, the jwt validation is not working(even the token is expired), did I misconfig anything?

Below are the 3 methods to call my api , I use the **expired token** to test:

method 1:  
 `curl --location 'http://localhost:8080/api/xxxx' --header 'Authorization: Bearer expiredToken' `
_returns 401_ (works as expected)

method 2, **no Authorization attribute in header**:  
 `curl --location 'http://localhost:8080/api/xxxx' `
**_expected to return 401 but returns 200_**

method 3, **the token has no _Bearer_** : 
  `curl --location 'http://localhost:8080/api/xxxx' --header 'Authorization: expiredToken' `
**_expected to return 401 but returns 200_**

**To Reproduce**
oauth2 jwt config as below(issuer-uri is the keycloak server)
```
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://abcd.com/auth/realms/athena-dev
          jwk-set-uri: https://abcd.com/auth/realms/athena-dev/protocol/openid-connect/certs
```

**oauth2 version**
org.springframework.security:spring-security-oauth2-resource-server:jar:**5.1.2.RELEASE**
and 
org.springframework.security:spring-security-oauth2-resource-server:jar:**6.2.4**
