### ISSUE TITLE
[Enhancement request] Integration between Spring oauth2 client and Spring Framework release 6 HttpInterface .attributes(clientRegistrationId("id")) for @HttpExchange @GetExchange

### ISSUE THREAD

**Issue by patpatpat123** [spring-projects/spring-security#16405]
**Context**

How has this issue affected you?
I am getting 401 without this enhancement request

What are you trying to accomplish?
```
@Configuration
public class RestClientConfig {

    @Bean
    public RestClient restClient(OAuth2AuthorizedClientManager authorizedClientManager, RestClient.Builder restClientBuilder) {
        OAuth2ClientHttpRequestInterceptor interceptor = new OAuth2ClientHttpRequestInterceptor(authorizedClientManager);
        return restClientBuilder
                .requestInterceptor(interceptor)
                .build();
    }

}
```

```
@RestController
public class LessonsController {

    private final RestClient restClient;

    public LessonsController(RestClient restClient) {
        this.restClient = restClient;
    }

    @GetMapping("/lessons")
    public String fetchLessons() {
        return restClient.get()
                .uri("https://someserver.om/someprotectedresource")
                .attributes(clientRegistrationId("my-client"))
                .retrieve()
                .body(String.class);
    }
}
```

```
spring:
  application:
    name: client-application
  security:
    oauth2:
      client:
        registration:
          my-client:
            provider: my-provider
            client-id: ididid
            client-secret: secretsecret
            authorization-grant-type: client_credentials
            scope: download
        provider:
          my-provider:
            token-uri: https://provider.com/token
```

After watching @Dan Vega's video, above is working. 
We have confirmation from the token provider we got the token, as well as from the resource server we got the resource, passing the token.
We now would like to do the same, with the new Spring Framework release 6 HttpInterface

What other alternatives have you considered?
Are you aware of any workarounds?

**Expected Behavior**

When doing this:

```
@Configuration
public class UserClientConfig {

    private final RestClient restClient;

    public UserClientConfig(OAuth2AuthorizedClientManager authorizedClientManager, RestClient.Builder restClientBuilder) {
        JdkClientHttpRequestFactory jdkClientHttpRequestFactory = new JdkClientHttpRequestFactory();
        OAuth2ClientHttpRequestInterceptor interceptor = new OAuth2ClientHttpRequestInterceptor(authorizedClientManager);
        this.restClient = restClientBuilder
                .requestInterceptor(interceptor)
                .requestFactory(jdkClientHttpRequestFactory)
                .baseUrl("https://host.com")
                .build();
    }

    @Bean
    public UserClient userClient() {
        RestClientAdapter adapter = RestClientAdapter.create(restClient);
        return HttpServiceProxyFactory.builderFor(adapter)
                .build()
                .createClient(UserClient.class);
    }

}
```

```
@HttpExchange(
        url = "/v1",
        accept = MediaType.APPLICATION_JSON_VALUE)
public interface UserClient {

    @GetExchange("/protectedresource/full")
    public User getUserById(@RequestParam Map<String, String> key value);

}
```

```
    @GetMapping("/lessons")
    public User fetchLessons() {
        return userClient.getUserById(Map.of("foo", "bar"));
    }
```

When using HttpInterface, this would not work.
The token is not fetch in the first place.
Maybe because of the lack of .attributes(clientRegistrationId("id")) for @HttpExchange @GetExchange
It would be great if HttpInterface can also work with token and token providers

**Current Behavior**

401 because no token
