### ISSUE TITLE
Support for using Azure WorkloadIdentity with Oauth2 Authorization Code Grant Flow

### ISSUE THREAD

**Issue by cprutle** [spring-projects/spring-security#16677]
**Expected Behavior**

You should be able to use the oauth2.client.registration to configure the application to use the Federated token for client authentication in the Oauth2 Authorization Code Grant Flow.

i.e.
```
    spring:
      security:
        oauth2:
          client:
            registration:
              azure:
                provider: azure
                client-id: <CLIENT_ID>
                federated-token-file-path: <PATH TO FILE>
                scope: <SCOPE LIST>

```

Spring Security should handle reading in the token file and updating it when the token expires and is rotated.  

The following parameters should be added to the request:

```
client_assertion_type: "urn:ietf:params:oauth:client-assertion-type:jwt-bearer"
client_assertion: <FEDERATED_TOKEN>

```

Implementation for spring-web is straight forward for non-reactive spring-web but will be more complex for reactive spring-webflux as reading a file is a blocking method.

**Current Behavior**

Currently this is not supported out of box.  It can be achieved through custom parameter converters.

**Context**

<!--- 
How has this issue affected you? We are using the client-secret method but our certificates are rotated often requiring us to regularly update kubernetes secrets
What are you trying to accomplish? The ability to use the microsoft azure provided managed identities so we do not have to maintain our own certificates and secrets
What other alternatives have you considered? Continue to use client-secrets or implement it myself
Are you aware of any workarounds? For the non-reactive spring-web flow, I implemented it by creating my own Parameter Converter class. Then in my DefaultSecurityFilterChain I set the TokenResponseClient to use the custom Converter.

```

 RestClientAuthorizationCodeTokenResponseClient authorizationCodeTokenResponseClient = new RestClientAuthorizationCodeTokenResponseClient();
        authorizationCodeTokenResponseClient.setParametersConverter(workloadIdentityParameterConverter);

....
 http.oauth2Login(httpSecurityOAuth2LoginConfigurer -> httpSecurityOAuth2LoginConfigurer
                    .tokenEndpoint(tokenEndpointConfig -> tokenEndpointConfig.accessTokenResponseClient(authorizationCodeTokenResponseClient)));
...

In the converter I had to manage reading in the token file during construction.  When a request was processed, I would have to check if the token was expired and if it was I would have to reread the token file to update to the new token.

I had not implemented a reactive flow yet.
-->
