### ISSUE TITLE
Support custom CAs in oauth login

### ISSUE THREAD

**Issue by gbaso** [spring-projects/spring-security#16920]
**Expected Behavior**

The internal rest clients should trust custom CAs.

**Current Behavior**

The internal clients only support CAs in the jdk truststore.

**Context**

In corporate environments sometime the identity provider is part of the corporate network and has an HTTPS certificate that is signed by the corporate CA.

Applications with oauth/oidc login perform several requests to the IdP, for retrieving metadata or for exchanging tokens. This is done with internal clients, for example in [ClientRegistrations](https://github.com/spring-projects/spring-security/blob/546dba7dc2657e22466ef38098ea898668ad1dc4/oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/registration/ClientRegistrations.java#L199) or in [AbstractRestClientOAuth2AccessTokenResponseClient](https://github.com/spring-projects/spring-security/blob/546dba7dc2657e22466ef38098ea898668ad1dc4/oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/endpoint/AbstractRestClientOAuth2AccessTokenResponseClient.java#L137), that are not configurable. While the latter allows to replace the `RestClient`, at the cost of having to reconfigure the message converters and status handler, the former does not.

The only avenue then is to add your custom CAs to the jdk truststore, usually done with the [ca-certificates](https://github.com/paketo-buildpacks/ca-certificates) buildpack. Unfortunately, loading CAs at runtime [doesn't seem to work in native image](https://github.com/spring-cloud/spring-cloud-bindings/issues/112).

It would be useful to be able to specify ssl bundles when configuring registrations via properties, and for those bundles to be applied to the internal clients.

**Comment by lbruun** [comment]
Similar issue encountered.

When the OAuth2 Authorization server is using a custom CA you really need to jump through an incredible amount of hoops.

I believe what is often missed is the fact that in a high-security environment we cannot just add CAs at the JVM level. In such an environment a CA is often only applicable for a specific outbound http connection, it must not apply to _any_ outbound http connection that the application makes.

Another issue encountered is the fact the an application may interact with _several_ OAuth2 Authorization Servers. And the same argument again: a given CA applies to a specific one. Not _any_ outbound connection to an OAuth2 Authorization Server.

## What we have

### Discovery or provider's config/metadata

Spring Security has a [feature](https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/oauth2/client/registration/ClientRegistrations.html#fromIssuerLocation(java.lang.String)) whereby you only need to specify the Authorization Server's issuer-url. From this Spring Security can discover the rest of the information it needs to know. This will not work if the endpoint uses a custom CA because the http client used to retrieve the metadata information is non-configurable.

### Customize the http client (RestTemplate / RestClient)

The docs at [Customize the RestOperations used by OAuth2 Client Components](https://docs.spring.io/spring-security/reference/servlet/oauth2/index.html#oauth2-client-customize-rest-operations) provides some guidance on how to customize the RestTemplate/RestClient used to interact with the Authorization Server. Note that those docs [refer to deprecated classes](https://github.com/spring-projects/spring-security/issues/17022) as of v.6.4. This aside, the recipe provided still falls short as it will apply to _any_ OAuth2 Provider used in the application, not a specific one.


## Ideal solution?

To fulfill requirements that the truststore configuration must be as targeted as possible, one can imagine that it would be possible to specify trust material on a per-provider basis, as in the following:

```yaml
spring:
  security:
    oauth2:
      client:
        registration:
          my-oidc-client-a:
            provider: my-oidc-provider-a
            client-id: my-client-id-a
            ...
          my-oidc-client-b:
            provider: my-oidc-provider-b
            client-id: my-client-id-b
            ...
        provider:
          my-oidc-provider-a:
            issuer-uri: https://my-oidc-provider-a.com
            ssl-bundle: my-bundle-a
            ...
          my-oidc-provider-b:
            issuer-uri: https://my-oidc-provider-b.com
            ssl-bundle: my-bundle-b
            ...
```

Only problem with the above proposal is that it uses a construct from Spring Boot, namely `SslBundle`. It is unfortunate that the `SslBundle` sits in Spring Boot and not Spring Framework as it would be ideal for this purpose. Perhaps there are other - and better - solutions?
