### ISSUE TITLE
Revisit oauth2 client properties hierarchy

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-security#4296]
### Summary

We need to ensure the _properties hierachy_ for configuring OAuth 2.0 clients makes sense.

With the current hierarchy, it may make sense to group _Provider_ specific properties together under a nested group.

As well, it may make sense to group _UserInfo_ specific properties under a nested group.

The following is the current  _properties hierachy_:

```
security:
  oauth2:
    client:
      google:
        client-id: client-id
        client-secret: client-secret
        client-authentication-method: header
        authorized-grant-type: authorization_code
        redirect-uri: "{scheme}://{serverName}:{serverPort}{baseAuthorizeUri}/{clientAlias}"
        scopes: openid, email, profile
        authorization-uri: "https://accounts.google.com/o/oauth2/auth"
        token-uri: "https://accounts.google.com/o/oauth2/token"
        user-info-uri: "https://www.googleapis.com/oauth2/v3/userinfo"
        user-info-converter: "org.springframework.security.oauth2.client.user.converter.UserInfoConverter"
        client-name: Google
        client-alias: google


```
