### ISSUE TITLE
OAuth2: Setting servlet context path doesn't change authorization URI

### ISSUE THREAD

**Issue by ghsnd** [spring-projects/spring-security#4510]
### Summary

Adding a servlet context path to the configuration of a Spring (Boot) application is not reflected in the authorization URI of the OAuth2 client.

### Working example

Following example works. Here is a piece of configuration extracted from `application.yml`:

```yaml
server:
  port: 443

...

security:
  oauth2:
    client:
      example-app:
        client-name: Example-app
        client-alias: example-app
        authorized-grant-type: authorization_code
        ...
```

Then, on the default "Login with OAuth 2.0" page, there appears a link `Example-app` pointing to `https://host.example.com/oauth2/authorization/code/example-app`. So far, so good.

### Failing example

Now I add a servlet context path to the configuration, because the application will run from `https://host.example.com/example` in stead of just `https://host.example.com`. Here is the change in config:

```yaml
server:
  port: 443
  servlet:
    context-path: /example

...
```
The client configuration stays the same.

Now, the link on the login page is still the same: `https://host.example.com/oauth2/authorization/code/example-app`, while it should be `https://host.example.com/example/oauth2/authorization/code/example-app`.

Is this an issue, or can this be overridden or configured in some way? I couldn't find it in the documentation. Thanks!
