### ISSUE TITLE
Occur the ParserException when specify '{baseUrl}/login/oauth2/code/{registrationId}' on yaml 

### ISSUE THREAD

**Issue by kazuki43zoo** [spring-projects/spring-security#4894]
### Summary

Occur the `ParserException` as follows:

```
...
	at com.example.demooauth2login.DemoOauth2LoginApplication.main(DemoOauth2LoginApplication.java:10)
Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
 in 'reader', line 14, column 13:
                clientId: foo
                ^
expected <block end>, but found Scalar
 in 'reader', line 17, column 43:
     ...   redirectUriTemplate: {baseUrl}/login/oauth2/code/{registrationId}
                                         ^

	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:571)
...
```

### Configuration

yml file:

```yaml
spring:
  security:
    oauth2:
      client:
        registration:
          yahoo:
            clientId: foo
            clientSecret: bar
            redirectUriTemplate: {baseUrl}/login/oauth2/code/{registrationId}
            authorizationGrantType: authorization_code
            scope:
              - openid
              - profile
              - email
            clientName: Yahoo! Japan
        provider:
          yahoo:
            authorizationUri: https://auth.login.yahoo.co.jp/yconnect/v2/authorization
            tokenUri: https://auth.login.yahoo.co.jp/yconnect/v2/token
            jwkSetUri: https://auth.login.yahoo.co.jp/yconnect/v2/jwks
            userInfoUri: https://userinfo.yahooapis.jp/yconnect/v2/attribute
```

### Version

* Spring Boot 2.0.0.M7
* Spring Security 5.0.0.RELEASE

### Solutions

It's work fine that surrounds the value by `'` as follows:

```diff
spring:
  security:
    oauth2:
      client:
        registration:
          yahoo:
            clientId: foo
            clientSecret: bar
-            redirectUriTemplate: {baseUrl}/login/oauth2/code/{registrationId}
+            redirectUriTemplate: '{baseUrl}/login/oauth2/code/{registrationId}'
            authorizationGrantType: authorization_code
            scope:
              - openid
              - profile
              - email
            clientName: Yahoo! Japan
        provider:
          yahoo:
            authorizationUri: https://auth.login.yahoo.co.jp/yconnect/v2/authorization
            tokenUri: https://auth.login.yahoo.co.jp/yconnect/v2/token
            jwkSetUri: https://auth.login.yahoo.co.jp/yconnect/v2/jwks
            userInfoUri: https://userinfo.yahooapis.jp/yconnect/v2/attribute
```

I'll suggest writing a notice for this behavior in reference document or [README of samples](https://github.com/spring-projects/spring-security/tree/master/samples/boot/oauth2login).
