### ISSUE TITLE
Support Custom Query Parameters within OAuth2AuthorizationRequestUriBuilder

### ISSUE THREAD

**Issue by andersonkyle** [spring-projects/spring-security#4911]
### Summary

When using a 3rd party OAuth provider such as Auth0 or Okta it would be very useful to allow developers to hook into the Authorization Request URI [build process](https://github.com/spring-projects/spring-security/blob/9f6af4f3b8e79a8a45369d99862cd3d96f4083ce/oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/web/OAuth2AuthorizationRequestUriBuilder.java#L38-L52) in order to add custom query parameters.  This is because the providers mentioned above have added additional parameters on top of the specification to allow for more functionality.

### Examples

---

[Auth0](https://auth0.com/docs/api/authentication#authorization-code-grant)

`audience: The unique identifier of the target API you want to access.`

This parameter impacts the format of the access token

---

[Okta](https://developer.okta.com/docs/api/resources/oauth2.html#obtain-an-authorization-grant-from-a-user)

`idp: The Identity provider used to do the authentication.`

This parameter instructs Okta to either use itself as the Identity Provider or to use another identity provider connected to the Okta Authorization Server.

---

A simple hook into the building of the URI should provide sufficient flexibility for these custom parameters and any others that are introduced in the future.

**Comment by jgrandja** [comment]
@andersonkyle Makes sense. We'll aim to add this for 5.1

**Comment by jgrandja** [comment]
@andersonkyle I'm finally circling back to address this requirement.

The simplest solution to allow for custom authorization request parameters would be to allow the user to provide the request parameters via the `ClientRegistration` configuration.

For example, if you would like to provide the `audience` and `idp` in the Authorization Request, you would configure it as follows:

```
spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: client-id
            client-secret: secret
	    ...
	    ...
        provider:
          okta:
            authorization-uri: https://tenant1.okta.com/oauth2/v2/auth?audience=resource1&idp=https://provider2.com
	   ...
	   ...
```

We would ensure that any request parameters supplied in the `authorization-uri` are preserved when building the Authorization Request.

Would this strategy meet your requirement?
