### ISSUE TITLE
Unit Testing Controllers of an OIDC Client

### ISSUE THREAD

**Issue by adenix** [spring-projects/spring-security#5120]
### Summary

Unable to find any documentation around unit testing controllers of a spring application configured as an OIDC client.

### Configuration

*application.yml*
---
```yaml
spring:
  security:
    oauth2:
      client:
        registration:
          VALUE:
            client-id: VALUE
            client-secret: VALUE
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            redirect-uri-template: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope: openid profile email
            client-name: VALUE
        provider:
          VALUE:
            authorization-uri: VALUE
            token-uri: VALUE
            user-info-uri: VALUE
            user-name-attribute: sub
            jwk-set-uri: VALUE
```

*WebSecurityConfiguration.java*
---
```java
@Configuration
@EnableWebSecurity
public class WebSecurityConfiguration extends WebSecurityConfigurerAdapter {

  @Inject
  private OAuth2ClientProperties oAuth2ClientProperties;

  @Override
  protected void configure(HttpSecurity http) throws Exception {
    http
        .csrf()
        .disable();

    http
        .authorizeRequests()
        .antMatchers(HttpMethod.GET, SecurityImageConstants.REQUEST_PREFIX + "/identities/*").permitAll()
        .antMatchers(SecurityImageConstants.REQUEST_PREFIX, SecurityImageConstants.REQUEST_PREFIX + "/**").authenticated()
        .anyRequest().permitAll()
        .and()
        .oauth2Login()
        .loginPage("/oauth2/authorization/" + getRegistrationId());
  }

  /**
   * Get the name of the first registration defined in {@link OAuth2ClientProperties}.
   *
   * NOTE: There should only ever be one registration for this application.
   *
   * @return The name of the first registration
   */
  private String getRegistrationId() {
    return oAuth2ClientProperties.getRegistration().keySet().iterator().next();
  }
}
```

### Version

```xml
<parent>
  <groupId>org.springframework.boot</groupId>
  <artifactId>spring-boot-starter-parent</artifactId>
  <version>2.0.0.RELEASE</version>
  <relativePath/>
</parent>
```

```xml
<dependency>
  <groupId>org.springframework.boot</groupId>
  <artifactId>spring-boot-starter-security</artifactId>
</dependency>
<dependency>
  <groupId>org.springframework.security</groupId>
  <artifactId>spring-security-oauth2-client</artifactId>
</dependency>
<dependency>
  <groupId>org.springframework.security</groupId>
  <artifactId>spring-security-oauth2-jose</artifactId>
</dependency>
```
