### ISSUE TITLE
OpenID Connect ".well-known" provider config

### ISSUE THREAD

**Issue by sparty02** [spring-projects/spring-security#5155]
### Summary

Currently, all of the OpenID Conenct provider configuration (authorization-uri, token-uri, user-info-uri, jwk-set-uri) can be established in the spring security environment using application.yml.  However, the OpenID Connect spec also [defines a ".well-known" discovery endpoint](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfig) that can be used to get all of this provider config as well.  The spring config should allow for some kind of "well-known" endpoint uri to be set that would then provide the rest of the related uris,

### Actual Behavior

All provider configuration must be explicitly defined in the application environment properties, e.g.:

```yaml
spring:
  security:
    oauth2:
      client:
        provider:
          okta:
            authorization-uri: https://dev-119999.oktapreview.com/oauth2/v1/authorize
            token-uri: https://dev-119999.oktapreview.com/oauth2/v1/token
            user-info-uri: https://dev-119999.oktapreview.com/oauth2/v1/userinfo
            jwk-set-uri: https://dev-119999.oktapreview.com/oauth2/v1/keys
            user-name-attribute: sub
```

### Expected Behavior

An abbreviated configuration could be done using the spec'ed "well-known" provider configuration discovery mechanism, e.g.:  

```yaml
spring:
  security:
    oauth2:
      client:
        provider:
          okta:
            openid-configuration-uri: https://dev-119999.oktapreview.com/.well-known/openid-configuration
```

Note, the above "openic-configuration-uri" is live and show an example of the spec'ed well-known openid-configuration uri.

### Version

5.0.3.RELEASE
