### ISSUE TITLE
I use spring-security-oauth2 as a client to connect UAA, but if UAA and my project have same IP address, it doesn't work. I don't know where the restrictions are?

### ISSUE THREAD

**Issue by jay763190097** [spring-projects/spring-security#5243]
### Summary

I use [UAA](https://github.com/cloudfoundry/uaa) as oauth2 server, and use spring-security-oauth2 as client, if they deploy in different IP address , It can work well. but if they deploy in same IP address, it doesn't work. 

### Configuration

```
security:
  ignored: /favicon.ico, /webjars/**, /css/**
  basic:
    enabled: false
  oauth2:
    client:
      client-id: idm
      client-secret: 123456
      access-token-uri: ${ssoServiceUrl}/oauth/token
      user-authorization-uri: ${ssoServiceUrl}/oauth/authorize
      scope:
       - openid
       - user_attributes
       - bc-admin
       - scim.*
       - clients.*
    resource:
      token-info-uri: ${ssoServiceUrl}/check_token
      jwt:
        key-uri: ${ssoServiceUrl}/token_key
      user-info-uri: ${ssoServiceUrl}/userinfo
```
```
@EnableOAuth2Sso
@Configuration
public class OAuth2SecurityConfig extends WebSecurityConfigurerAdapter {
    @Override
    public void configure(WebSecurity web) throws Exception {
        super.configure(web);
    }

    @Override
    protected void configure(HttpSecurity http) throws Exception {
        http.csrf().disable();
        //@formatter:off
        http.authorizeRequests()
                .antMatchers("/login**")
                    .authenticated()
                .antMatchers("/client/**")
                    .authenticated()
                .antMatchers("/group/**")
                    .authenticated()
                .antMatchers("/user/**")
                    .authenticated()
                .antMatchers("/")
                    .permitAll()
                .anyRequest()
                    .authenticated();
        //@formatter:on

    }

}
```

### Version

```
<dependency>
            <groupId>org.springframework.security.oauth</groupId>
            <artifactId>spring-security-oauth2</artifactId>
            <version>2.0.7.RELEASE</version>
        </dependency>
```
