### ISSUE TITLE
Support OIDC login_hint for clients

### ISSUE THREAD

**Issue by tnwang** [spring-projects/spring-security#5244]
### Summary

Support applications acting as clients providing their arbitrary values for OIDC login hint. This is passed along via the `login_hint` parameter during the OpenID Authentication Request.

It is standard to represent the user you want to use to login, but as per spec this can be customized for use by the identity provider (spec later mentions it as a string value parameter). As such, applications could be passing dynamic values (e.g. username provided by user to client, or in the case of UAA the application may choose to perform custom logic to determine which identity provider should be used).

http://openid.net/specs/openid-connect-core-1_0.html#AuthRequest

> login_hint
>
> OPTIONAL. Hint to the Authorization Server about the login identifier the End-User might use to log in (if necessary). This hint can be used by an RP if it first asks the End-User for their e-mail address (or other identifier) and then wants to pass that value as a hint to the discovered authorization service. It is RECOMMENDED that the hint value match the value used for discovery. This value MAY also be a phone number in the format specified for the phone_number Claim. The use of this parameter is left to the OP's discretion.

**Comment by jgrandja** [comment]
Related #4911

**Comment by jgrandja** [comment]
Hi @tnwang. I'm currently looking at implementing this feature. This is what I'm thinking.

The simplest solution to allow for custom authentication request parameters would be to allow the user to provide the request parameters via the `ClientRegistration` configuration.

For example, if you would like to provide the `login_hint ` in the Authentication Request, you would configure it as follows:

```
spring:
  security:
    oauth2:
      client:
        registration:
          uaa:
            client-id: client-id
            client-secret: secret
	    ...
	    ...
        provider:
          uaa:
            authorization-uri: https://tenant1.uaa.com/oauth2/v2/auth?login_hint=thehint
	   ...
	   ...
```

We would ensure that any request parameters supplied in the `authorization-uri` are preserved when building the Authentication Request.

Would this strategy meet your requirement?
