### ISSUE TITLE
OAuth2AccessTokenResponseClient and OAuth2UserService support the implementation of custom requests.

### ISSUE THREAD

**Issue by XYUU** [spring-projects/spring-security#5373]
### Summary
Can specify the request build method for OAuth2AccessTokenResponseClient, support custom ClientAuthenticationMethod implementation.

The request build method can be specified for OAuth2UserService to support the implementation of a custom request.

**Comment by jgrandja** [comment]
@XYUU It is not clear to me what you are looking for? Can you please provide more detail.

**Comment by XYUU** [comment]
Add an interface that can add a custom request to OAuth2AccessTokenResponseClient so that you can specify which implementation to use in ClientRegistration.

such as:
```
spring:
  security:
    oauth2:
      client:
        registration:
          alipay:
            provider: alipay
            client-id: your-app-client-id
            client-secret: your-app-client-secret
            client-authentication-method: custom
            authorization-grant-type: authorization_code
            redirect-uri-template: {baseUrl}/{action}/oauth2/code/{registrationId}
            scope: basic
            client-name: alipay
```

Using the above configuration, I can specify an implementation named "custom".
