### ISSUE TITLE
How to use service name as part of authorization-uri for the provider of the oauth2 client

### ISSUE THREAD

**Issue by tomcatGu** [spring-projects/spring-security#6449]
Here is my application.yml:
...
  security:
    oauth2:
      client:
        registration:
          test:
            client-id: webapp
            client-secret: 123456
            authorization-grant-type: authorization_code
            redirect-uri-template: http://localhost:6601/login/oauth2/code/test
        provider:
          test:
            authorization-uri: http://localhost:9000/oauth/authorize
            token-uri: http://localhost:9000/oauth/token
            jwt-key-uri: http://localhost:9000/oauth/token_key
            user-info-uri: http://localhost:9000/user
            userNameAttribute: user_name
...

Here is my WebClientConfig：
...
    @Bean
    WebClient webClient(ReactiveClientRegistrationRepository clientRegistrationRepository,
                        ServerOAuth2AuthorizedClientRepository authorizedClientRepository) {
        ServerOAuth2AuthorizedClientExchangeFilterFunction oauth = new ServerOAuth2AuthorizedClientExchangeFilterFunction(
                clientRegistrationRepository, authorizedClientRepository);
        oauth.setDefaultOAuth2AuthorizedClient(true);

        return WebClient.builder().filter(oauth).build();
    }
 ...

I want to replace "localhost:9000" with "oauth2-service".

What should I do? Thx.

**Comment by jgrandja** [comment]
@tomcatGu If you have a question or need help with a specific topic, please search for an answer on StackOverflow first. If you can't find the answer than please post your question on StackOverflow. If you don't get an answer on StackOverflow after a few days, feel free to create a ticket with a link to the StackOverflow question. Our preference is to keep GitHub issues for bug reports or new feature and enhancement requests.

Having said that please see [Placeholders in Properties](https://docs.spring.io/spring-boot/docs/2.1.2.RELEASE/reference/htmlsingle/#boot-features-external-config-placeholders-in-properties).

For example:

```yaml
service-name: https://oauth2-service.google.com

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: client-id-1234
            client-secret: client-secret-1234
        provider:
          google:
            authorization-uri: ${service-name}/oauth2/v1/authorize
```
