### ISSUE TITLE
Use proxy to get access token

### ISSUE THREAD

**Issue by rexave** [spring-projects/spring-security#6472]
### Summary

While using the sample provided by @spencergibb at https://github.com/spring-cloud-samples/sample-gateway-oauth2login , i couldn't configure the gateway to use http proxy.

### Actual Behavior

The webclient used for that isn't configurable. 
`org.springframework.security.oauth2.client.endpoint.WebClientReactiveAuthorizationCodeTokenResponseClient#webClient`

### Expected Behavior

Can you make this configurable or inject a webclient bean to let use configure it ?

### Configuration

```
spring: 
  cloud:
    gateway:
      httpclient:
        proxy:
          host: myProxy.com
          port: 1234
      enabled: true
```

### Version

Version used : 2.1.2.RELEASE

### Sample

https://github.com/spring-cloud-samples/sample-gateway-oauth2login

(redirected from https://github.com/spring-projects/spring-security-oauth2-boot/issues/81)
