### ISSUE TITLE
Using issuer-uri with Spring Security OAuth + Okta: name "Okta" not displayed

### ISSUE THREAD

**Issue by mraible** [spring-projects/spring-security#6795]
### Summary

If I integrating Spring Security OAuth into a Spring Boot project and specify the following settings, everything works as expected:

```yml
spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 31793bb7e921df27aa91
            client-secret: 8743bde0b87d28bc8e989d14a673601463182cfb
          okta:
            client-id: 0oakbxx90o3rIwhUi0h7
            client-secret: gpL7sLOCgabuMeSoKo0CjiFDwpEIXfsN71PMpUTx
        provider:
          okta:
            authorization-uri: https://dev-737523.oktapreview.com/oauth2/default/v1/authorize
            token-uri: https://dev-737523.oktapreview.com.oktapreview.com/oauth2/default/v1/token
            user-info-uri: https://dev-737523.oktapreview.com.oktapreview.com/oauth2/default/v1/userinfo
            jwk-set-uri: https://dev-737523.oktapreview.com.oktapreview.com/oauth2/default/v1/keys
```

By "expected", I mean both "GitHub" and "Okta" show up on the login form.

<img width="1077" alt="Screen Shot 2019-04-16 at 10 14 22 AM" src="https://user-images.githubusercontent.com/17892/56226590-c4534900-6030-11e9-9ed2-940c971a9736.png">

However, if I simplify the configuration and only specify an `issuer-uri`, the issuer URI is shown instead of "Okta".

```yml
spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 31793bb7e921df27aa91
            client-secret: 8743bde0b87d28bc8e989d14a673601463182cfb
          okta:
            client-id: 0oakbxx90o3rIwhUi0h7
            client-secret: gpL7sLOCgabuMeSoKo0CjiFDwpEIXfsN71PMpUTx
        provider:
          okta:
            issuer-uri: https://dev-737523.oktapreview.com/oauth2/default
```

<img width="1077" alt="Screen Shot 2019-04-16 at 10 14 43 AM" src="https://user-images.githubusercontent.com/17892/56226640-e2b94480-6030-11e9-9f51-389c785453f8.png">

### Actual Behavior

GitHub is displayed, along with the Okta issuer URI.

### Expected Behavior

GitHub is displayed, as is "Okta".

### Version

Spring Boot 2.1.4

**Comment by jgrandja** [comment]
@mraible This behaviour is expected.

By default, the `issuer-uri` is used for `ClientRegistration.clientName` when the `ClientRegistration` is resolved using OpenID Connect discovery - see `ClientRegistrations.fromOidcIssuerLocation()`.

However, when **not** using OpenID Connect discovery, as in the first configuration than `ClientRegistration.clientName` defaults to `Okta`  - see `CommonOAuth2Provider.OKTA`.

Makes sense?

**Comment by mraible** [comment]
@jgrandja This logic seems odd because the information (`provider.okta`) is there even with OIDC discovery. Are you saying that if all URIs are present, then the name calculation is different?

**Comment by jgrandja** [comment]
@mraible 

> the information (`provider.okta`) is there even with OIDC discovery

`provider.okta` is used for the `clientRegistrationId` which is different than what is displayed in the login page - "Okta" comes from `ClientRegistration.clientName` == "Okta" via `CommonOAuth2Provider.OKTA`.

> Are you saying that if all URIs are present, then the name calculation is different?

Yes, the name calculation is different. If OpenID Connect Discovery is used (because `issuer-uri` is present) than `ClientRegistrations.fromOidcIssuerLocation()` is called which defaults `ClientRegistration.clientName` to `issuer-uri`. On the other end, if `issuer-uri` is **not present**, than `ClientRegistration.clientName` defaults to `clientName` in `CommonOAuth2Provider.OKTA`.

If you would like `ClientRegistration.clientName` to default to `CommonOAuth2Provider.OKTA` **when OpenID Connect Discovery is used** than this change would need to happen on the Boot side. Specifically, in `OAuth2ClientPropertiesRegistrationAdapter.getBuilderFromIssuerIfPossible()`. Feel free to log an issue there if you require.

In the meantime, you can specify a `clientName` as follows:

```yml
spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: 0oakbxx90o3rIwhUi0h7
            client-secret: gpL7sLOCgabuMeSoKo0CjiFDwpEIXfsN71PMpUTx
            client-name: Okta
        provider:
          okta:
            issuer-uri: https://dev-737523.oktapreview.com/oauth2/default
```
