### ISSUE TITLE
id_token being ignored in OAuth2AuthorizationCodeAuthenticationProvider.authenticate method

### ISSUE THREAD

**Issue by pivotal-jamil-shamy** [spring-projects/spring-security#6965]
### Summary
Looking at the [oauth2-protocol-patterns](https://github.com/jgrandja/oauth2-protocol-patterns) sample, let's assume that in the [UI App](https://github.com/jgrandja/oauth2-protocol-patterns/tree/master/ui-app) we have this spring security oauth2 configuration:

```
spring:
  security:
    oauth2:
      client:
        registration:
          login-client:
            provider: uaa-1
            client-id: login-client
            client-secret: secret
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid,profile,email
          client-a:
            provider: uaa-2
            client-id: client-a
            client-secret: secret
            redirect-uri: "{baseUrl}/flow-a"
            scope: authority-a,openid,profile,email
        provider:
          uaa-1:
            issuer-uri: http://localhost:8091/uaa/oauth/token
          uaa-2:
            issuer-uri: http://localhost:8092/uaa/oauth/token
```

**An important difference to note compared to the original sample:** we are requesting the `openid,profile,email` scopes in `client-a` configuration. We are intentionally requesting the `openid` scope to get back an `id-token` from `uaa-2`.

### Actual Behavior

Taking the [FlowAController.java](https://github.com/jgrandja/oauth2-protocol-patterns/blob/master/ui-app/src/main/java/sample/web/FlowAController.java) as an example, it seems that when the user authenticates with `uaa-2` to authorize the `ui-app` (through `client-a`) to do some actions on their behalf, the `id_token` is not propagated downstream, even if the `openid` scope is requested.

The `OAuth2AccessTokenResponse` returns the `id-token` as an additional parameter in the `additionalParameters` map, but it is being ignored when constructing a new instance of `OAuth2AuthorizationCodeAuthenticationToken` in `OAuth2AuthorizationCodeAuthenticationProvider.authenticate` method.

### Expected Behavior
We would like like to have access to the `id_token` sent back by `uaa-2`.
Is there a way to get it? Or are we configuring something wrong? 

### Version
Spring Security 5.1.5
