### ISSUE TITLE
OAuth2 sso with OAuth2RestTemplate M-2-M returns to the login page of the authentication server

### ISSUE THREAD

**Issue by 344654931** [spring-projects/spring-security#7243]
### Actual Behavior

return to the login page of the authentication server after calling the service

### Expected Behavior
oss client2：hello world client1

### Version 
spring-security-oauth2-core:5.1.5.RELEASE

### AuthorizationServer
```
@Configuration
@EnableAuthorizationServer
public class AuthorizationServerConfig extends AuthorizationServerConfigurerAdapter {

    @Autowired
    private JwtConfig jwtConfig;

    @Autowired
    private DataSource dataSource;

    @Override
    public void configure(AuthorizationServerSecurityConfigurer security) throws Exception {
        security.allowFormAuthenticationForClients();
        security.tokenKeyAccess("isAuthenticated()");
    }

    @Override
    public void configure(ClientDetailsServiceConfigurer clients) throws Exception {
        clients.jdbc(dataSource);
    }

    @Override
    public void configure(AuthorizationServerEndpointsConfigurer endpoints) throws Exception {
        endpoints.accessTokenConverter(jwtAccessTokenConverter());
        endpoints.tokenStore(jwtTokenStore());
    }


    @Bean
    public JwtTokenStore jwtTokenStore() {
        return new JwtTokenStore(jwtAccessTokenConverter());
    }

    @Bean
    public JwtAccessTokenConverter jwtAccessTokenConverter() {
        JwtAccessTokenConverter jwtAccessTokenConverter = new JwtAccessTokenConverter();
        jwtAccessTokenConverter.setSigningKey(jwtConfig.getKey());
        return jwtAccessTokenConverter;
    }

}
```
#### yml config
```
server:
  port: 8080
spring:
  application:
    name: sso-auth-server
```
---
#### OAuth2RestTemplate  config
```
@SpringBootApplication
public class ClientApplication1 {
    public static void main(String[] args) {
        SpringApplication.run(ClientApplication1.class, args);
    }


    @Bean
    @ConfigurationProperties(prefix = "security.oauth2.client")
    public ClientCredentialsResourceDetails resourceDetails() {
        ClientCredentialsResourceDetails details = new ClientCredentialsResourceDetails();
        return details;
    }

    @Bean
    public OAuth2RestTemplate getRestTemplate() {
        OAuth2RestTemplate template = new OAuth2RestTemplate(resourceDetails(), new DefaultOAuth2ClientContext());
        return template;
    }
}
```
#### request code
```
    @GetMapping("/test")
    @ResponseBody
    public String test(HttpServletRequest request) {

        String urlClient2 = "http://localhost:8083/client2/api/get?name=client1";
        String resultClient = restTemplate.getForObject(urlClient2, String.class);
        System.out.println("ssoclient resp："+resultClient);

        return resultClient;
    }
```
#### yml config
```
server:
  port: 8082
  servlet:
    context-path: /client1
spring:
  application:
    name: sso-client1
auth:
  server: http://localhost:8080

security:
  oauth2:
    client:
      client-id: client1
      client-secret: user123
      user-authorization-uri: ${auth.server}/oauth/authorize
      access-token-uri: ${auth.server}/oauth/token
    resource:
      jwt:
        key-uri: ${auth.server}/oauth/token_key
```
---
#### api/get method
```
@RestController
public class ApiController {

    @RequestMapping(value = "/api/get", method = RequestMethod.GET)
    @ResponseBody
    public String findAllByStatus(@RequestParam("name") String name) {
        return "oss client2：hello world " + name;
    }

}
```
#### yml config
```
server:
  port: 8083
  servlet:
    context-path: /client2
spring:
  application:
    name: sso-clinet2
auth:
  server: http://localhost:8080

security:
  oauth2:
    client:
      client-id: client2
      client-secret: user123
      user-authorization-uri: ${auth.server}/oauth/authorize
      access-token-uri: ${auth.server}/oauth/token
      pre-established-redirect-uri:
    resource:
      jwt:
        key-uri: ${auth.server}/oauth/token_key
```
