### ISSUE TITLE
Response url drops the port number causing an invalid_redirect_uri_parameter error when runing behing a reverse proxy

### ISSUE THREAD

**Issue by fnaeem78** [spring-projects/spring-security#7416]
### Summary
I have got nginx as a ssl-term and reverse-proxy listening on 9443. Even though the redirect-uri-template is set correctly, the response url doesnt include port 9443, the comparison fails and an OAuth2Authentication is thrown. 

I am using XforwardedFor and XProto in my nginx and useForwardedHeaders is true in the spring application.yml. 

### Actual Behavior

The response and request uri doesnt match and an authentication is thrown. 

### Expected Behavior
The URIs should match and the user should be authenticated. 
### Configuration

```
server:
  port: 5500
  max-http-header-size: 16384
  use-forward-headers: true
#  tomcat:
#    internal-proxies: .*
spring:
  security:
    oauth2:
      client:
        registration:
          azure:
            client-id:{Removed}
            client-secret: {Removed}
            authorization-grant-type: authorization_code
            redirect-uri-template: https://localhost:9443/login/oauth2/code/azure
            scope:
              - openid
              - profile
              - email
              - offline_access
        use-current-uri: true
        provider:
          azure:
            authorization-uri: https://login.microsoftonline.com/{DIR_ID}/oauth2/v2.0/authorize
            token-uri: https://login.microsoftonline.com/{DIR_ID}/oauth2/v2.0/token
            user-info-uri: https://graph.microsoft.com/oidc/userinfo
            jwk-set-uri: https://login.microsoftonline.com/{DIR_ID}/discovery/v2.0/keys
            user-name-attribute: name
```
```
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $host:$server_port;
proxy_set_header Host $host:$server_port;
proxy_set_header X-Forwarded-Proto $scheme;
```

### Version

org.springframework.security:spring-security-oauth2-client:jar:5.1.5.RELEASE
org.springframework.boot:spring-boot-starter-web:jar:2.1.6.RELEASE
org.springframework:spring-core:jar:5.1.8.RELEASE
###Sample
The redirect url address from request and response objects is dropping the 9443 port causing an OAuth2AuthenticationException
