### ISSUE TITLE
404 On Cloud Gateway with Oauth and @EnableAuthorizationServer

### ISSUE THREAD

**Issue by lafual** [spring-projects/spring-security#7524]
I have a number of Webflux processes all being authenticated by a central Authorisation and Resource server. This is working fine, however when I add the Spring Gateway and try to access the Webflux via the Gateway, I am getting "Invalid Client Registration Id" on the Gateway. I have been using the following as a reference [Securing Services with Spring Cloud Gateway](https://spring.io/blog/2019/08/16/securing-services-with-spring-cloud-gateway) except without using UAA.

My Authorisation/Resource is as follows;
```
Spring Boot 2.1.9
org.springframework.boot:spring-boot-starter-security
org.springframework.security.oauth.boot:spring-security-oauth2-autoconfigure
org.springframework.security:spring-security-oauth2-jose
org.springframework.boot:spring-boot-starter-web

server:
  port: 8889

@SpringBootApplication
@EnableAuthorizationServer
@EnableResourceServer
public class Application {
	public static void main(String[] args) {
		SpringApplication.run(Application.class, args);
	}
}

@Configuration
public class AuthServerConfig extends AuthorizationServerConfigurerAdapter  {
	
	@Autowired
	private BCryptPasswordEncoder passwordEncoder;
	
	@Override
	public void configure(AuthorizationServerSecurityConfigurer security) throws Exception {
		security
			.tokenKeyAccess("permitAll()")
			.checkTokenAccess("isAuthenticated()");
	}
	
	@Override
		public void configure(ClientDetailsServiceConfigurer clients) throws Exception {
			clients.inMemory()
				.withClient("myClientId2")
				.secret(passwordEncoder.encode("mySecret2"))
				.authorizedGrantTypes("authorization_code")
				.scopes("all")
				.autoApprove(true)
				.redirectUris("http://localhost:8083/login/oauth2/code/myAppTwo") 
				.and()
				.withClient("myGatewayId")
				.secret(passwordEncoder.encode("myGatewaySecret"))
				.authorizedGrantTypes("authorization_code")
				.scopes("all")
				.autoApprove(true)
				.redirectUris("http://localhost:8888/login/oauth2/code/gateway") 
				;
		}
}

@Configuration
@Order(1)
public class SecurityConfig extends WebSecurityConfigurerAdapter {

	@Override
	protected void configure(HttpSecurity http) throws Exception {
		http.csrf().disable()
			.requestMatchers()
			.antMatchers("/login", "/oauth/authorize")
			.and().authorizeRequests().anyRequest().authenticated()
			.and().formLogin().permitAll();
	}
	
	@Override

	protected void configure(AuthenticationManagerBuilder auth) throws Exception {
		auth.inMemoryAuthentication()
			.withUser("x")
			.password(passwordEncoder().encode("123"))
			.roles("USER");
	}
	
	@Bean
	public BCryptPasswordEncoder passwordEncoder() {
		return new BCryptPasswordEncoder();
	}
}

@RestController
public class UserController {

		@GetMapping("/user/me")
		public Principal user(Principal principal) {
			System.err.println(principal);
			return principal;
		}
}
```

The Webflux is;

```
Boot: 2.1.9.RELEASE
org.springframework.boot:spring-boot-starter-webflux
org.springframework.boot:spring-boot-starter-security
org.springframework.boot:spring-boot-starter-oauth2-client

server:
  port: 8083
spring:
  security:
    oauth2:
      client:
        registration:
          myAppTwo:
            client-id: myClientId2
            client-secret: mySecret2
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          myAppTwo:
            authorization-uri: http://localhost:8889/oauth/authorize
            token-uri: http://localhost:8889/oauth/token
            user-info-uri: http://localhost:8889/user/me
            user-name-attribute: name 

@SpringBootApplication
public class Test1Application {
	public static void main(String[] args) {
		SpringApplication.run(Test1Application.class, args);
	}
}

@RestController
public class Controller {
	@GetMapping(value = "/test3")
	Mono<OAuth2User> getTest3(@AuthenticationPrincipal Mono<OAuth2User> ouser) {
		return ouser;
	}
}
```

The above works fine.

However when I add the Gateway;

```
Boot: 2.1.9.RELEASE
org.springframework.boot:spring-boot-starter-webflux
org.springframework.boot:spring-boot-starter-oauth2-client
org.springframework.cloud:spring-cloud-starter-gateway
org.springframework.cloud:spring-cloud-starter-security

server:
  port: 8888
spring:
  autoconfigure:
    exclude: org.springframework.boot.actuate.autoconfigure.security.reactive.ReactiveManagementWebSecurityAutoConfiguration
  cloud:
    gateway:
      routes:
      - id: route2
        predicates:
          - Path=/2/**
        uri: http://localhost:8083
        filters:
          - RewritePath=/2/(?<myPath>.*), /$\{myPath} 
  security:
    oauth2:
      client:
        registration:
          gateway:
            client-id: myGatewayId
            client-secret: myGatewaySecret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          gateway:
            authorization-uri: http://localhost:8889/oauth/authorize
            token-uri: http://localhost:8889/oauth/token
            user-info-uri: http://localhost:8889/user/me
            user-name-attribute: name 
            jwk-set-uri: http://localhost:8889/oauth/token_key

@SpringBootApplication
public class Gateway1Application {
	public static void main(String[] args) {
		SpringApplication.run(Gateway1Application.class, args);
	}
}
```

Then run ```http:localhost:8888/2/test3``` I get;

For the Webflux;

```
HTTP GET "/test3", headers={masked}
Completed 302 FOUND, headers={masked}
```

For the Authorisation/Resource Server, it seems to pass authorisation;

```
Writing [org.springframework.security.oauth2.provider.OAuth2Authentication@d8a7c2c1: Principal: org.springframework.security.core.userdetails.User@78: Username: x; Password: [PROTECTED]; Enabled: true; AccountNonExpired: true; credentialsNonExpired: true; AccountNonLocked: true; Granted Authorities: ROLE_USER; Credentials: [PROTECTED]; Authenticated: true; Details: remoteAddress=127.0.0.1, tokenType=BearertokenValue=<TOKEN>; Granted Authorities: ROLE_USER]
Completed 200 OK, headers={masked}
Chain processed normally
SecurityContextHolder now cleared, as request processing completed
```

And for the Gateway;

```
[268ce0a6] HTTP GET "/2/test3"
[268ce0a6] Completed 302 FOUND
0:0:0:0:0:0:0:1 - - [12/Oct/2019:20:58:40 +0300] "GET /2/test3 HTTP/1.1" 302 0 8888 4 ms
[268ce0a6] HTTP GET "/oauth2/authorization/gateway"
[268ce0a6] Completed 302 FOUND
0:0:0:0:0:0:0:1 - - [12/Oct/2019:20:58:40 +0300] "GET /oauth2/authorization/gateway HTTP/1.1" 302 0 8888 2 ms
HTTP GET "/login/oauth2/code/gateway?code=9wqVfa&state=ib9q8tSco0taoeiA_rqp8o7N1ydN8T4AXgIaIQOrqH4%3D"
HTTP POST http://localhost:8889/oauth/token
Writing form fields [grant_type, code, redirect_uri] (content masked)
Response 200 OK
Decoded [{access_token=689165aa-968b-4c8a-9e83-b612709313cd, token_type=bearer, expires_in=40824, scope=all}]
[54578239] HTTP GET http://localhost:8889/user/me
[54578239] Response 200 OK
[54578239] Decoded [{authorities=[{authority=ROLE_USER}], details={remoteAddress=127.0.0.1, sessionId=null, tokenValue=6 (truncated)...]
[268ce0a6] Completed 302 FOUND
0:0:0:0:0:0:0:1 - - [12/Oct/2019:20:58:40 +0300] "GET /login/oauth2/code/gateway?code=9wqVfa&state=ib9q8tSco0taoeiA_rqp8o7N1ydN8T4AXgIaIQOrqH4%3D HTTP/1.1" 302 0 8888 132 ms
HTTP GET "/2/test3"
Route matched: route2
Mapping [Exchange: GET http://localhost:8888/2/test3] to Route{id='route2', uri=http://localhost:8083, order=0, predicate=Paths: [/2/**], match trailing slash: true, gatewayFilters=[[[RewritePath /2/(?<myPath>.*) = '/${myPath}'], order = 1]]}
[268ce0a6] Mapped to org.springframework.cloud.gateway.handler.FilteringWebHandler@5c4f5e26
Sorted gatewayFilterFactories: [[GatewayFilterAdapter{delegate=org.springframework.cloud.gateway.filter.RemoveCachedBodyFilter@3ae9d1e2}, order = -2147483648], [GatewayFilterAdapter{delegate=org.springframework.cloud.gateway.filter.AdaptCachedBodyGlobalFilter@43f0c2d1}, order = -2147482648], [GatewayFilterAdapter{delegate=org.springframework.cloud.gateway.filter.NettyWriteResponseFilter@5477a1ca}, order = -1], [GatewayFilterAdapter{delegate=org.springframework.cloud.gateway.filter.ForwardPathFilter@670d4d38}, order = 0], [GatewayFilterAdapter{delegate=org.springframework.cloud.gateway.filter.GatewayMetricsFilter@43b40233}, order = 0], [[RewritePath /2/(?<myPath>.*) = '/${myPath}'], order = 1], [GatewayFilterAdapter{delegate=org.springframework.cloud.gateway.filter.RouteToRequestUrlFilter@41522537}, order = 10000], [GatewayFilterAdapter{delegate=org.springframework.cloud.gateway.config.GatewayNoLoadBalancerClientAutoConfiguration$NoLoadBalancerClientFilter@23eff5d1}, order = 10100], [GatewayFilterAdapter{delegate=org.springframework.cloud.gateway.filter.WebsocketRoutingFilter@131ff6fa}, order = 2147483646], [GatewayFilterAdapter{delegate=org.springframework.cloud.gateway.filter.NettyRoutingFilter@25cd49a4}, order = 2147483647], [GatewayFilterAdapter{delegate=org.springframework.cloud.gateway.filter.ForwardRoutingFilter@e9dc4d0}, order = 2147483647]]
[268ce0a6] Completed 302 FOUND
0:0:0:0:0:0:0:1 - - [12/Oct/2019:20:58:40 +0300] "GET /2/test3 HTTP/1.1" 302 0 8888 16 ms
[268ce0a6] HTTP GET "/oauth2/authorization/myAppTwo"
[268ce0a6] Resolved [ResponseStatusException: 400 BAD_REQUEST "Invalid client registration id"] for HTTP GET /oauth2/authorization/myAppTwo

```

Now on the Gateway, I see via debug that ```DefaultServerOAuth2AuthorizationRequestResolver.findByRegistrationId``` first checks ```gateway``` and passes. However, it tries and fails on a second pass for ```myAppTwo```, which was not defined the Gateway's YML and I assume shouldn't be.

So why am I getting this error? (Sorry for the very long question). Admittedly, from the quoted article, I had omitted the code for the ```TokenRelayGatewayFilterFactory```, but I don't see the Gateway trying to hit that URL, so I assume that this is not relevant... yet...
