### ISSUE TITLE
Spring Security OIDC Redirect Port Changes

### ISSUE THREAD

**Issue by piacenti** [spring-projects/spring-security#7638]
### Summary
Need to keep port when getting OIDC redirects
Spring Boot Application with Spring Security

### Actual Behavior
In my application.yml file I have the following under an oauth2 client registration

> redirect-uri: "{baseUrl}/login/oauth2/code/ping"

When hitting https://localhost:8080/someURL it initiates OIDC it redirects to 
https://localhost:8443/someURL
It changes the port even though initial call was already HTTPS.

This is a problem when testing integration of secured applications locally. I can't have them all running at the same time off of port 8443
Documentation states that we can have non standard ports with this config.
`<port-mappings>
    <port-mapping http="9080" https="9443"/>
</port-mappings>
`

However, what is the yaml equivalent of that for Spring Boot? (none are provided in the docs I found).

### Expected Behavior

With 
> redirect-uri: "{baseUrl}/login/oauth2/code/ping"

When hitting https://localhost:8080/someURL and OIDC flow takes place, it should not change the port of an already HTTPS connection.

### Configuration

```yml
security:
    oauth2:
      client:
        provider:
          ping:
            ...
        registration:
          ping:
            client-id: ${OIDC_CLIENT_ID}
            client-secret: ${OIDC_CLIENT_SECRET}
            provider: ping
            scope: ...
            redirect-uri: "{baseUrl}/login/oauth2/code/ping"
            client-name: oidc
            registration-id: ping
            authorization-grant-type: authorization_code
```
### Version

Spring Boot 2.2.0.RELEASE
Spring Security 5.2.0.RELEASE
