### ISSUE TITLE
Add possibility to insert extra form data parameter when getting access token with oauth2 client_credential flow

### ISSUE THREAD

**Issue by jpiccaluga** [spring-projects/spring-security#7781]
### Summary

Some OIDC/OAuth2 provider like Auth0 requires audience parameter set in the post body when calling /oauth/token endpoint to retrieve access token with the client_credentials flow. They do this because an machine to machine client could potentially get access to multiple api resource server. 
In order to make client_credentials work with OAuth2 provider specificity we need to re-implement a custom OAuth2AccessTokenResponseClient or ReactiveOAuth2AccessTokenResponseClient to include the missing require field (audience or what ever provider specificity).

It will be very appreciate if we can add free extra parameters to the request body when calling token endpoint. For example we can add an extra property as a Map<String, String> in the ClientRegistration class and add it to the body on OAuth2ClientCredentialsGrantRequestEntityConverter and WebClientReactiveClientCredentialsTokenResponseClient.

### Actual Behavior

When trying client_credential flow with Auth0 I got 403 could not retrieve token because the audience parameter is not specified in the request.

### Expected Behavior

Get status code 200 and retrieve access token form Auth0 provider

### Configuration

application.yml
```
spring:
  application:
    name: user-mangement
  security:
    oauth2:
      client:
        provider:
          oauth0Management:
            token-uri: https://<redacted>/oauth/token
        registration:
          oauth0Management:
            client-authentication-method: POST
            authorization-grant-type: client_credentials
            client-id: <redacted>
            client-secret: <redacted>
            scope: read:users
```

```
@Bean
WebClient webClient(ReactiveClientRegistrationRepository clientRegistrations) {
    ServerOAuth2AuthorizedClientExchangeFilterFunction oauth =
      new ServerOAuth2AuthorizedClientExchangeFilterFunction(
        clientRegistrations,
        new UnAuthenticatedServerOAuth2AuthorizedClientRepository());
    oauth.setDefaultClientRegistrationId("oauth0Management");
    return WebClient.builder()
      .filter(oauth)
      .build();
}
```

### Version
spring-security -> 5.2.1

**Comment by jgrandja** [comment]
@jpiccaluga It is already possible to customize the Access Token request. Take a look at the [reference doc](https://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/#customizing-the-access-token-request-3) where you can specify a custom `DefaultClientCredentialsTokenResponseClient.setRequestEntityConverter()`.

For the reactive side, you can supply a custom `WebClient` to `WebClientReactiveClientCredentialsTokenResponseClient.setWebClient()` configured with an `ExchangeFilterFunction` that could modify the request by adding the additional parameter(s). See this [comment](https://github.com/spring-projects/spring-security/issues/7709#issuecomment-564464304) for an example. NOTE: The example performs response post-processing so in your case you would use `ExchangeFilterFunction.ofRequestProcessor()` for request pre-processing.

I'm going to close this issue since this capability is already available. Please let me know if I missed something.

**Comment by jpiccaluga** [comment]
@jgrandja Thanks for your response. 
My concern with this approach is that we have to splits the configuration. With spring boot it will give something like this.
```
spring:
  application:
    name: my-app
  security:
    oauth2:
      client:
        provider:
          oauth0Management:
            token-uri: https://<redacted>/oauth/token
        registration:
          oauth0Management:
            client-authentication-method: POST
            authorization-grant-type: client_credentials
            client-id: <redacted>
            client-secret: <redacted>
            scope: read:users
          anOtherClient:
            client-authentication-method: POST
              authorization-grant-type: client_credentials
              client-id: <redacted>
              client-secret: <redacted>
              scope: read:users

registration-ext:
  oauth0Management:
    audience: "http://test/api"
    whatever: "toto"
  anOtherClient:
    audience: "http://test/api"
```
This is not very elegant.

Something like this is preferable:
```
spring:
  application:
    name: my-app
  security:
    oauth2:
      client:
        provider:
          oauth0Management:
            token-uri: https://<redacted>/oauth/token
        registration:
          oauth0Management:
            client-authentication-method: POST
            authorization-grant-type: client_credentials
            client-id: <redacted>
            client-secret: <redacted>
            scope: read:users
            additional-form-data:
              audience: "http://test/api"
              whatever: "toto"
          anOtherClient:
            client-authentication-method: POST
              authorization-grant-type: client_credentials
              client-id: <redacted>
              client-secret: <redacted>
              scope: read:users
              additional-form-data:
                audience: "http://test/api"
                whatever: "toto"
```
What do you think?

**Comment by jpiccaluga** [comment]
This is not a lot of code to change. If you agree on that it will be more readable and easier for a developer to understand how to enrich the form data, I can submit you a PR.
Let me know.
Cheers

**Comment by jgrandja** [comment]
@jpiccaluga 

Given the proposed additional configuration:

```yaml
additional-form-data:
              audience: "http://test/api"
              whatever: "toto"
```

Which specific endpoint is posted `additional-form-data`? This name is too generic as there are multiple points where requests are made via the client protocols, eg. Authorization Request, Token Request, and UserInfo request. There are a few others as well.

The biggest issue with this configuration approach is that the form data is `static`. This is a huge drawback when you need to derive form data from the environment/application in a dynamic way.

Furthermore, adding this type of application configuration causes unnecessary complexity to the `yaml`. I like to keep things simple and clean so this type of data - custom form parameters - is an advanced customization and is recommended to customize via the specific feature component.
