### ISSUE TITLE
SAML2: Wrong IdP response URL throws NPE (for non-existing "RelyingParty")

### ISSUE THREAD

**Issue by berschmoe** [spring-projects/spring-security#7865]
### Summary
Configure an invalid response URL at the identity provider (using nonconfigured registration id) a _NullPointerException_ occurs during authentication process.

E.g. _registrationId_ is _okta_ (at your service provider) but at the identity provider the configured response URL is _http://mydomain/login/saml2/sso/anythingElse_.

The _Saml2WebSsoAuthenticationFilter_ does not check if the requested "RelyingParty" exits. If the _RelyingPartyRegistrationRepository_ return _null_, processing not stopped.

```
java.lang.NullPointerException: null
	at org.springframework.security.saml2.provider.service.servlet.filter.Saml2Utils.getServiceProviderEntityId(Saml2Utils.java:86) ~[spring-security-saml2-service-provider-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.security.saml2.provider.service.servlet.filter.Saml2WebSsoAuthenticationFilter.attemptAuthentication(Saml2WebSsoAuthenticationFilter.java:81) ~[spring-security-saml2-service-provider-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:212) ~[spring-security-web-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	[..]
```

### Expected Behavior
no NPE :-)

### Version
5.2.1.RELEASE

**Comment by eleftherias** [comment]
Thanks for the report @berschmoe. Could you please provide a minimal sample that reproduces this issue?

**Comment by berschmoe** [comment]
It can be reproduce with a unit test or the SAML2 sample.

#### Unit Test
This test method (for _Saml2WebSsoAuthenticationFilterTests_) simulates the behavior. "CASE 2" throws the _NullPointerException_. The mocked _RelyingPartyRegistrationRepository_ behaves the same as the implementation - if no entry exists, it returns _null_.

```
@Test
public void attemptAuthenticationWhenRegistrationIdExitsThenReturnAuthentication() {
	AuthenticationManager authenticationManager = mock(AuthenticationManager.class);
	given(authenticationManager.authenticate(any(Authentication.class))).willAnswer(a->a.getArgument(0));

	given(repository.findByRegistrationId("idp-registration-id")).willReturn(mock(RelyingPartyRegistration.class));
	   
	filter = new Saml2WebSsoAuthenticationFilter(repository, "/some/other/path/{registrationId}");
	filter.setAuthenticationManager(authenticationManager);

	// CASE 1: registrationId exits
	request.setPathInfo("/some/other/path/idp-registration-id");
	request.setParameter("SAMLResponse", "response");
	   
	Assert.assertNotNull( filter.attemptAuthentication( request, response ) );

	// CASE 2: registrationId not exits
	request.setPathInfo("/some/other/path/notExits");
	request.setParameter("SAMLResponse", "response");
	   
	Assert.assertNull( filter.attemptAuthentication( request, response ) );
}
```

#### Spring Boot 2.x Sample
To reproduce this behavior in "real life" you can use the Spring Boot 2.x Sample project (https://docs.spring.io/spring-security/site/docs/5.2.1.RELEASE/reference/htmlsingle/#samllogin-sample-boot)
I used Okta as identity provider and change the _application.yml_ file (_saml2login_ project).

```
spring:
  security:
    saml2:
      relyingparty:
        registration:
          okta:
            signing:
              credentials:
                - private-key-location: "file:/saml/app.key"
                  certificate-location: "file:/saml/app.crt"
            identityprovider:
              verification:
                credentials:
                  - certificate-location: "file:/saml/okta.cert"
              entity-id: http://www.okta.com/exk28lgiqnHTxxxxxx
              sso-url: https://dev.okta.com/app/myuser_app_1/exk28lgiqnHTxxxxxx/sso/saml
```

Now I setup up Okta and make a small spelling mistake - instead of _okta_ I wrote _otak_.

![2020-01-28_11h50_39](https://user-images.githubusercontent.com/58601803/73258539-31059180-41c6-11ea-9378-3eba3b822bb1.png)

Launch Spring Boot application, open http://localhost:8080 and you will be caught in an endless loop. The app redirect to Okta, Okta redirect to the app (with the wrong registration id), the NPE occurs. App redirect to Okta, Okta redirect ...
