### ISSUE TITLE
Autoconfig bearer only clients OIDC

### ISSUE THREAD

**Issue by haris-zynka** [spring-projects/spring-security#8008]
### Summary

I'm trying to connect Keycloak and Spring Boot with Webflux (Kotlin) and I'm trying to pass Keycloak token as Bearer in Authorization header. Spring Boot App is set as Bearer only client.

### Actual Behavior

Redirects me to root URL of Keycloak server

### Expected Behavior

It would be good if Spring Security could detect Authorization header nad try to verify it without redirection to root URL

### Configuration
Before I only used 
```yaml
  security:
    oauth2:
      client:
        registration:
          x-users:
            client-id: xxx
            client-secret: xxx
        provider:
          x-users:
            authorization-uri: https://xxx/auth/
            token-uri: https://xxx/auth/realms/test/protocol/openid-connect/token
            user-info-uri: https://xxx/auth/realms/test/protocol/openid-connect/userinfo
            user-name-attribute: sub
            jwk-set-uri: https://xxx/auth/realms/test/protocol/openid-connect/certs
            issuer-uri: https://xxx/auth/realms/test
```
### Version

5.2.1 Release
