### ISSUE TITLE
java.lang.IllegalArgumentException: serverWebExchange cannot be null when using WebClient with client_credentials 

### ISSUE THREAD

**Issue by cipriandumitrel** [spring-projects/spring-security#8230]
### Summary

From my service I am performing http calls to an external service OAuth2 protected. The flow that we are using for the communication is "client_credentials".  I am using not the RestTemplate http client but the WebClient. The WebClient is configured like this:

```java
@Bean
  WebClient webClient(ReactiveClientRegistrationRepository reactiveClientRegistrationRepository,
                      ServerOAuth2AuthorizedClientRepository serverOAuth2AuthorizedClientRepository) {

    ClientCredentialsReactiveOAuth2AuthorizedClientProvider provider =
            new ClientCredentialsReactiveOAuth2AuthorizedClientProvider();
    provider.setAccessTokenResponseClient(new WebClientReactiveClientCredentialsTokenResponseClient());

    DefaultReactiveOAuth2AuthorizedClientManager manager =
            new DefaultReactiveOAuth2AuthorizedClientManager(reactiveClientRegistrationRepository,
                    serverOAuth2AuthorizedClientRepository);

    manager.setAuthorizedClientProvider(provider);

    ServerOAuth2AuthorizedClientExchangeFilterFunction oauth2 =
            new ServerOAuth2AuthorizedClientExchangeFilterFunction(manager);

    oauth2.setDefaultClientRegistrationId(CLIENT_REGISTRATION_ID);

    WebClient client = WebClient.builder()
            .baseUrl(externalApiSettings.getUri())
            .filter(oauth2)
            .build();

    return client;
  }
```

### Actual Behavior

When I perform the call like this:

```java
@Component
@Log4j2
@RequiredArgsConstructor
class Client {

  private final WebClient client;

  @EventListener(ApplicationReadyEvent.class)
  public void ready() {

    this.client
            .get()
            .uri(uriBuilder -> uriBuilder
                    .path("/api/v3/{tenant}/{entity}")
                    .queryParam("view", "flat")
                    .queryParam("version", "1")
                    .queryParam("state", "update")
                    .queryParam("fromSeq", "58000")
                    .queryParam("toSeq", "58100")
                    .build("nl", "contactchannels"))
            .retrieve()
            .bodyToFlux(String.class)
            .subscribe(entity -> log.info("Entity: " + entity));
  }

}
```
, I get IllegalArgumentException: 

```java 
java.lang.IllegalArgumentException: serverWebExchange cannot be null
``` 
, and debugging I can see that getTokenResponse method from WebClientReactiveClientCredentialsTokenResponseClient is never reached. Before that, I was building the webclient using the non-reactive ClientRegistrationRepository and OAuth2AuthorizedClientRepository.  I am sure that I am missing something but I don't know what. 

### Configuration

```yaml
logging:
  level:
    org.springframework.web.reactive.function.client.WebClient: DEBUG
external:
  uri: https://external_url
spring:
  application:
    name: cdm_client
  http:
    log-request-details: true
  security:
    oauth2:
      client:
        provider:
          idam:
            token-uri: "https://idam_token_hostname/authorize/api/oauth2/access_token"
        registration:
          idam:
            client-id: CLIENT_ID
            client-secret: CLIENT_SECRET
            authorization-grant-type: client_credentials

```

### Sample
https://github.com/cipriandumitrel/oauth2-client
