### ISSUE TITLE
Sign in with Apple Oauth2 Support

### ISSUE THREAD

**Issue by codeconsole** [spring-projects/spring-security#9047]
**Summary:**
Apple now forces app developers to provide Sign in with Apple if they want to submit apps that currently use oath2 with other providers.  Spring Security should offer a default `CommonOAuth2Provider.APPLE` implementation to ease the configuration process.

```
	APPPLE {

		@Override
		public Builder getBuilder(String registrationId) {
			ClientRegistration.Builder builder = getBuilder(registrationId, ClientAuthenticationMethod.POST,
					DEFAULT_REDIRECT_URL);
			builder.scope("openid", "name", "email");
			builder.authorizationUri("https://appleid.apple.com/auth/authorize?response_mode=form_post");
			builder.tokenUri("https://appleid.apple.com/auth/token");
			builder.jwkSetUri("https://appleid.apple.com/auth/keys");
			builder.clientName("Apple");
			return builder;
		}

	}
```

Note: 
At this time apple does not support userInfoUri.  I believe information such as user email is only provided during the first authentication.

https://developer.apple.com/sign-in-with-apple/get-started/
https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_rest_api

**Comment by jgrandja** [comment]
Thanks for the suggestion @codeconsole 

> Spring Security should offer a default `CommonOAuth2Provider.APPLE` implementation to ease the configuration process

Alternatively, you could define this in your `application.yml`


```yaml
spring:
  security:
    oauth2:
      client:
        registration:
          apple:
            client-id: apple-client-id
            client-secret: apple-client-secret
        provider:
          apple: 
            authorization-uri: https://appleid.apple.com/auth/authorize?response_mode=form_post
            token-uri: https://appleid.apple.com/auth/token
            jwk-set-uri: https://appleid.apple.com/auth/keys
```

I believe this is simple enough. We also don't want to add too many standard providers in `CommonOAuth2Provider` since those endpoints may change and it would be much easier (and quicker) to change the configuration in `application.yml` instead of waiting for the next release of Spring Security that contains the update in `CommonOAuth2Provider`. I don't think we'll be adding further standard configurations in `CommonOAuth2Provider` given the ease of adding it in `application.yml`.

I'm going to close this issue based on the explanation as per above.

**Comment by SelanDeemantha** [comment]
@codeconsole  hi, I have faced with that same problem. Did you find out a way to configure the apple sign with spring security?

**Comment by codeconsole** [comment]
> @codeconsole hi, I have faced with that same problem. Did you find out a way to configure the apple sign with spring security?

yeah, just used the code I pasted above and it worked fine `APPPLE { ... }`

**Comment by SelanDeemantha** [comment]
@codeconsole hi, I am really struggling to connect Apple Sign In with Spring Security .Can you share a sample working code how we can add `APPLE { ... }` to CommonOAuth2Provider and how we can use the authorization Code which are sent in body to token exchange and get logged user details.

**Comment by jgrandja** [comment]
@SelanDeemantha @codeconsole It appears that Apple has changed their client authentication requirements from `client_secret` to `private_key_jwt`. See this [comment](https://github.com/spring-projects/spring-security/issues/8175#issuecomment-784377963) for more details.

@codeconsole Does your code still work with `client_secret`?

**Comment by SelanDeemantha** [comment]
@jgrandja, @thomas-corte  Thanks for pointing out that. Even though I have changed `client_secret` to `private_key_jwt`, my code is not working. It always throws [invalid_client] exception and again redirect to login page after getting `authorization_code` by logging with Apple identity provider.
I am not sure whether I need to write a custom redirect handler with oauth2 client for access the code and continue, because Apple is used a post request and they send data in body.
[https://developer.okta.com/blog/2019/06/04/what-the-heck-is-sign-in-with-apple](url)

I used this below rubby script to generate `client_secret`.

```
require 'jwt'

key_file = 'key.txt'
team_id = ''
client_id = ''
key_id = ''

ecdsa_key = OpenSSL::PKey::EC.new IO.read key_file

headers = {
  'kid' => key_id
}

claims = {
	'iss' => team_id,
	'iat' => Time.now.to_i,
	'exp' => Time.now.to_i + 86400*180,
	'aud' => 'https://appleid.apple.com',
	'sub' => client_id,
}

token = JWT.encode claims, ecdsa_key, 'ES256', headers

puts token
```

I used below `.yml` configuration file.

```
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 429751581-------xxxxxxxx------sercontent.com
            clientSecret: bPVX-xxxxxxxx--ambXNVu
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          facebook:
            clientId: 429751581-------xxxxxxxx------122334
            clientSecret: bPVX-xxxxxxxx--ambXNVu
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile
          apple:
            clientId: com.xyz.dwd.id
            privateKeyJwt: eyJraWQiOiJBWkJYTYifQ.eyJpc3MiXXXXXXXOiJxNjE0MTYyNjYzLCXXXXXXXXXJleHAiOjE2Mjk3MTQ2NjMsImFS5jb20iLCJzdWIiOiJjb20uYVydXXXXXXXXmljZS5pZCJ9.HnSyBUKomO8Qa21e2nBuxuo5oe-XXvfywYQWiGO_ggWrK24qHA
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - name
            authorizationGrantType: authorization_code
            responseMode: form_post
            responseType: code
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)
          apple:
            authorizationUri: https://appleid.apple.com/auth/authorize?response_mode=form_post
            tokenUri: https://appleid.apple.com/auth/token
            jwkSetUri: https://appleid.apple.com/auth/keys
			
auth:
  token:
    secret: kdksjuuyyyyxxxxx0988w76ghd6
    expire.seconds: 18000 #5 hours
    refresh.expire.seconds: 86400 # one day
  authorized.redirect.uris: http://localhost:3000/oauth2/redirect,http://localhost:8060/,http://localhost:8060/swagger-ui.html,http://localhost:4200/,demoapp://oauth2/redirect,qaapp://oauth2/redirect
```
			
Still I couldn't be able to  connect `Apple_Sign_In` with oauth2 client. If someone can share a working code example, it's grateful.

**Comment by codeconsole** [comment]
@jgrandja I use `client-secret`

Here is my **working** `application.yml`

```
                   apple:
                        client-id: apple-client-id
                        client-secret: apple-client-secret
                        authorization-grant-type: authorization_code
                        redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
                        scope: openid, name, email
                        client-name: Apple
                        client-authentication-method: post
                provider:
                    apple:
                        authorization-uri: https://appleid.apple.com/auth/authorize?response_mode=form_post
                        token-uri: https://appleid.apple.com/auth/token
                        jwk-set-uri: https://appleid.apple.com/auth/keys
                        user-name-attribute: sub
```

It is important to note that without `client-authentication-method: post` you will get `invalid_client` because Apple does not accept get requests.

**Comment by SelanDeemantha** [comment]
@codeconsole Thank you very much for quick response. After adding `client-authentication-method: post` to` .yml` file `invalid_client` exception has gone. I have to write custom redirect handler to get` UserInfo` via `DefaultOidcUser`. Finally, I was able to integrate Apple also as an Authentication Provider.

**Comment by kirvinod** [comment]
Hi @SelanDeemantha  

Do you mind sharing your custom filter, initially had same issue `invalid_client`

I added `client-authentication-method: post`

which solved that issue but getting `missing_user_info_uri`

If i add openid in scope i get other error `oidc_provider_not_configured`


my config looks like this:

```
spring.security.oauth2.client.registration.apple.client-id=com.******.login
spring.security.oauth2.client.registration.apple.client-secret= *****
spring.security.oauth2.client.registration.apple.authorization-grant-type= authorization_code
spring.security.oauth2.client.registration.apple.redirect-uri= {baseUrl}/oauth2/callback/{registrationId}
spring.security.oauth2.client.registration.apple.scope=name, email
spring.security.oauth2.client.registration.apple.client-authentication-method= post
spring.security.oauth2.client.registration.apple.client-name= Apple

spring.security.oauth2.client.provider.apple.authorization-uri=https://appleid.apple.com/auth/authorize?response_mode=form_post
spring.security.oauth2.client.provider.apple.token-uri=https://appleid.apple.com/auth/token
spring.security.oauth2.client.provider.apple.jwk-set-uri=https://appleid.apple.com/auth/keys
spring.security.oauth2.client.provider.apple.user-name-attribute=sub
```

**Comment by codeconsole** [comment]
@kirvinod You need to create your own user details service.  Apple does not have a a user info uri.

**Comment by kirvinod** [comment]
@codeconsole thanks for help. I have created user details service already. For other providers facebook, google etc I am not getting any error. Below returns null for apple along with missing_user_info_uri

For reference I am using this tutorial: https://www.callicoder.com/spring-boot-security-oauth2-social-login-part-1/

```
 private OAuth2User processOAuth2User(OAuth2UserRequest oAuth2UserRequest, OAuth2User oAuth2User) {
        System.out.println(oAuth2User.getAttributes());
}
```

**Comment by codeconsole** [comment]
> @codeconsole thanks for help. I have created user details service already. For other providers facebook, google etc I am not getting any error. Below returns null for apple along with missing_user_info_uri
> 
> For reference I am using this tutorial: https://www.callicoder.com/spring-boot-security-oauth2-social-login-part-1/
> 
> ```
>  private OAuth2User processOAuth2User(OAuth2UserRequest oAuth2UserRequest, OAuth2User oAuth2User) {
>         System.out.println(oAuth2User.getAttributes());
> }
> ```

Apple is an `OidcUserRequest`

**Comment by ftore** [comment]
@codeconsole I am trying to implement Apple sign-in as per your suggestion, and I am getting `authorization_request_not_found` error. The HttpSession is being dropped after redirecting to `https://appleid.apple.com/auth/authorize` website. Here is my config:

```
spring:
  security:
    oauth2:
      client:
        registration:
          apple:
            client-id: ${APPLE_CLIENT_ID}
            client-secret: ${APPLE_CLIENT_SECRET}
            client-authentication-method: post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/api/login/oauth2/code/{registrationId}"
            scope: openid,name,email
            client-name: Apple
        provider:
          apple:
            authorization-uri: https://appleid.apple.com/auth/authorize?response_mode=form_post
            token-uri: https://appleid.apple.com/auth/token
            jwk-set-uri: https://appleid.apple.com/auth/keys
            user-name-attribute: sub
```

also, I created custom `CustomOidcUserService` that does custom logic. So far, Google auth is working just fine, no issue with session, but Apple is not working.
