### ISSUE TITLE
Consent scopes belong to multiple resource servers

### ISSUE THREAD

**Issue by chenrujun** [spring-projects/spring-security#9207]
**Expected Behavior**

In spring-security-oauth2-client,
when multiple clientRegistrations use the same provider,
by one user-consent operation,
resource owner can consent scopes belong to **multiple** resource servers ,
and put **multiple** authorizedClients into OAuth2AuthorizedClientRepository.

**Current Behavior**

when multiple clientRegistrations use the same provider,
by one user-consent operation,
resource owner can consent scopes belong to **only one** resource servers ,
and put **only one** authorizedClients into OAuth2AuthorizedClientRepository.

**Context**

For example, develop have clientRegistration1 and clientRegistration2, both client registration the use same provider.
We have the requirement to put both clientRegistration1 and clientRegistration2 by one consent operation.

Here is a workaround to satisfy this requirement: https://github.com/Azure/azure-sdk-for-java/pull/17325/commits/5885067ab4e84f24912912157e74470ffc74d313

**Comment by jgrandja** [comment]
Apologies @chenrujun, but I'm not understanding your use case.

Can you put together a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates your use case so I can better understand.

**Comment by chenrujun** [comment]
Hi, @jgrandja , Thank you for your response.

Here is the sample:
https://github.com/chenrujun/spring-security-issues-9207-sample/blob/master/src/main/resources/application.yml
```
spring:
  security:
    oauth2:
      client:
        provider:
          provider-one:
            authorization-uri: blabla
            token-uri: blabla
        registration:
          registration-one:
            provider: provider-one
            client-id: blabla
            client_secret: blabla
            scope: scope-one-one, scope-one-two
          registration-two:
            provider: provider-one
            client-id: blabla
            client_secret: blabla
            scope: scope-two-one, scope-two-two
```
In this configuration, `registration-one` and `registration-two` use the same provider: `provider-one`. 
I need this function: after user login in `provider-one`'s login page, both `registration-one` and `registration-two` exist in [OAuth2AuthorizedClientRepository](https://github.com/spring-projects/spring-security/blob/master/oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/web/OAuth2AuthorizedClientRepository.java)

**Comment by jgrandja** [comment]
@chenrujun The sample you provided does not qualify as a [minimal reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example). The only code in there is `@SpringBootApplication` and `application.yml`.

Either way, I now understand what you are trying to achieve.

The 2 options are as follows:

### Option 1

Change `application.yml` to:

```yaml
spring:
  security:
    oauth2:
      client:
        provider:
          provider-one:
            authorization-uri: blabla
            token-uri: blabla
        registration:
          registration-one:
            provider: provider-one
            client-id: blabla
            client_secret: blabla
            scope: scope-one-one, scope-one-two, scope-two-one, scope-two-two
```

After user is logged in then redirect to `/authorize-client`

```java
@GetMapping("/authorize-client")
public String authorizeClient(
		@RegisteredOAuth2AuthorizedClient("registration-one") OAuth2AuthorizedClient authorizedClient) {

	return "index";
}
```

`authorizedClient` will have an access token with all scopes required: `scope-one-one, scope-one-two, scope-two-one, scope-two-two`


### Option 2

Keep `application.yml` as-is:

```yaml
spring:
  security:
    oauth2:
      client:
        provider:
          provider-one:
            authorization-uri: blabla
            token-uri: blabla
        registration:
          registration-one:
            provider: provider-one
            client-id: blabla
            client_secret: blabla
            scope: scope-one-one, scope-one-two
          registration-two:
            provider: provider-one
            client-id: blabla
            client_secret: blabla
            scope: scope-two-one, scope-two-two
```

After user is logged in then redirect to `/authorize-two-clients`

```java
@GetMapping("/authorize-two-clients")
public String authorizeTwoClients(
		@RegisteredOAuth2AuthorizedClient("registration-one") OAuth2AuthorizedClient authorizedClient1,
		@RegisteredOAuth2AuthorizedClient("registration-two") OAuth2AuthorizedClient authorizedClient2) {

	return "index";
}
```

`authorizedClient1` and `authorizedClient2` are now available to call resource servers.


For future reference, questions are better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements.

I'm going to close this as both solutions will work for your use case.
