### ISSUE TITLE
Disable redirect to oauth2/authorization/{registrationId} in oauth2 flow?

### ISSUE THREAD

**Issue by SMakhrov** [spring-projects/spring-security#9261]
Hi!
Is it possible to disable redirect to oauth2/authorization/{registrationId} in oauth2 flow?
I have following properties for oauth2 flow in Spring Cloud Gateway, but nowhere I didn't specify url oauth2/authorization/{registrationId}:

```
security:
    oauth2:
      client:
        registration:
          smart_hub_client:
            provider: wso2is
            client-id: gateway
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/redirect_uri"
            scope: openid
        provider:
          wso2is:
            authorization-uri: http://localhost:8090/uaa/oauth/authorize
            token-uri: http://uaa:8090/uaa/oauth/token
            user-info-uri: http://uaa:8090/uaa/userinfo
            user-name-attribute: sub
            jwk-set-uri: http://uaa:8090/uaa/token_keys
```
But I see it in my request chain:
![image](https://user-images.githubusercontent.com/60988212/101112165-c5fac780-35ed-11eb-9d2b-b3332bb4004c.png)

The Request URL from screenshot is here: https://uaa:8090/oauth2/authorization/smart_hub_client

**Comment by eleftherias** [comment]
Hi, @SMakhrov. I saw your SO post, please avoid cross-posting support requests. StackOverflow is a great place for help, and team members all allocate dedicated time to be on there answering questions. Posting there will make it clearer for community members who run into similar issues.

For reference, here is the origin SO post: https://stackoverflow.com/questions/65136895/disable-redirect-to-oauth2-authorization-registrationid-in-oauth2-client-flow

**Comment by SMakhrov** [comment]
After investigation with colleagues it looks like bug.
**Expected behaviour:**
1. Request to https://gateway/index.html
2. Redirect to https://gateway/login.html
3. _Entering credentials_
4. Redirect to https://authserver/oauth2/authorize?sessionDataKey=9bef122b-d088-4398-871c-d898c4241e13
5. Redirect to https://gateway/redirect_uri?code=445c0856-8285-372a-8fbb-e9322a94106a&state=3f9ed239281746a8bb8c7e63a21f368f&session_state=2e683a3520c491d6f98863725bdc6ae000507a851a7b32776da66269ef7f205b.XiIA96b7-WdAEtwKZRMvHQ
6. Response with 200 on page https://gateway/index.html

**Actual behaviour:**
1. Request to https://gateway/index.html
2. Redirect to https://gateway/login.html
3. _Entering credentials_
4. Redirect to https://authserver/oauth2/authorize?sessionDataKey=9bef122b-d088-4398-871c-d898c4241e13
5. Redirect to https://gateway/redirect_uri?code=445c0856-8285-372a-8fbb-e9322a94106a&state=3f9ed239281746a8bb8c7e63a21f368f&session_state=2e683a3520c491d6f98863725bdc6ae000507a851a7b32776da66269ef7f205b.XiIA96b7-WdAEtwKZRMvHQ
6. Redirect to https://gateway/oauth2/authorization/smart_hub_client
Eternal cycle from 2 step to 6.

application.yaml
```
server:
  port: 80
spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: root
          uri: http://gateway
          predicates:
            - Path=/**
          filters:
            - RemoveRequestHeader=Cookie

  security:
    oauth2:
      client:
        registration:
          smart_hub_client:
            provider: wso2is
            client-id: myclientid
            client-secret: mysecret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/redirect_uri"
            scope: sso,openid
        provider:
          wso2is:
            authorization-uri: http://authserver/oauth2/authorize?loginPage=login.jsp
            token-uri: http://authserver/oauth2/token
            user-info-uri: http://authserver/oauth2/userinfo
            user-name-attribute: sub
            jwk-set-uri: http://authserver/oauth2/jwks 

```
